import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
type Decision = 'pass' | 'reject'
interface Note { decision: Decision; categories: string[]; rationale: string }
interface Candidate { word: string; sentenceId: number; sentence: string; reviewType: string; semanticDecisionSource: string }
interface Provenance { sentenceId: number; source: string; qualityScore: number; [key: string]: number | string }
interface PriorRow extends Candidate, Note { [key: string]: unknown }
const root = resolve(import.meta.dirname, '..'); const auditRoot = resolve(root, 'audit/v1.3-context-final-semantic')
const candidates = JSON.parse(await readFile(resolve(auditRoot, 'blind-validation-candidates.json'), 'utf8')) as { seed: number; rows: Candidate[] }
const provenance = JSON.parse(await readFile(resolve(root, 'data-source/examples/example-provenance.json'), 'utf8')) as Record<string, Provenance>
const priorRows = (await Promise.all([1, 2, 3].map(async (attempt) => JSON.parse(await readFile(resolve(auditRoot, `blind-validation-attempt-${attempt}.json`), 'utf8')).rows as PriorRow[]))).flat()
const priorByPair = new Map(priorRows.map((row) => [`${row.word.toLocaleLowerCase()}::${row.sentenceId}`, row]))
const manual: Record<number, Note> = {
  4: { decision: 'pass', categories: [], rationale: "Detecting other dimensions parallel to this one gives parallel a clear side-by-side relationship meaning in a concise science context." },
  5: { decision: 'pass', categories: [], rationale: "Finding peace in the absence of conflict gives absence a direct not-present meaning." },
  8: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "An intergalactic voyage is a science-fiction setting, so humanity is not anchored in a normal default-learning context." },
  14: { decision: 'pass', categories: [], rationale: "Amplifying a debate with thoughtless responses gives amplify a clear increase-or-intensify meaning." },
  15: { decision: 'pass', categories: [], rationale: "Competing claims along a porous, undefined border give border a clear geographic-boundary meaning." },
  19: { decision: 'pass', categories: [], rationale: "Hair samples testing whether medication suppresses a virus gives accurate a clear reliable-test meaning in a factual science context." },
  20: { decision: 'pass', categories: [], rationale: "A museum section housing additional exhibitions gives additional a direct more-than-before meaning." },
  22: { decision: 'pass', categories: [], rationale: "Asking why challenges occurred in an academic record gives occur a clear happen meaning." },
  26: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "A literally walking, talking skeleton is a supernatural image that does not provide a normal useful default context for skeleton." },
  33: { decision: 'pass', categories: [], rationale: "Asking whether a friar is a priest gives priest a clear religious-role comparison in an accessible question." },
  36: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "Describing autism through a verbal/nonverbal contrast makes verbal depend on a sensitive diagnostic and identity context rather than a neutral example." },
  44: { decision: 'pass', categories: [], rationale: "Encouraging eligible community members to submit applications gives submit a clear formal-delivery meaning." },
  48: { decision: 'pass', categories: [], rationale: "A restaurant not catering for vegans gives cater a clear provide-food-for-a-group meaning." },
  53: { decision: 'pass', categories: [], rationale: "Going against the grain is a common idiom that clearly demonstrates grain in a figurative direction-against use." },
  55: { decision: 'pass', categories: [], rationale: "A garden project teaching patience gives project a clear planned activity meaning." },
  56: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "Invariant virtue and uninterrupted vice form an abstract philosophical argument, so virtue is not anchored in a concrete default-learning context." },
  64: { decision: 'reject', categories: ['hate', 'public-controversy'], rationale: "Calling political opponents pedophiles as a propaganda tactic is explicit hostile identity discourse, making conservative a severe unsuitable context." },
  68: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "Opposition to cancel culture as a lucrative industry is a niche political-media controversy rather than a neutral context for cancel." },
  71: { decision: 'pass', categories: [], rationale: "Needing sleep and relaxation for the brain to function gives function a clear operate-properly meaning." },
  74: { decision: 'pass', categories: [], rationale: "Birds indicating the health of ecology gives ecology a clear study-of-environment-and-living-systems meaning." },
  77: { decision: 'reject', categories: ['medical-heavy'], rationale: "Asking what cancer stages and grades mean is a sensitive diagnostic-information context unsuitable as a default example for cancer." },
  78: { decision: 'pass', categories: [], rationale: "Life being a series of choices or a single path gives series a clear sequence-of-events meaning in an understandable question." },
  79: { decision: 'pass', categories: [], rationale: "A duchess carrying herself with dignity and grace gives dignity a clear composed-self-respect meaning." },
  90: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Being born on a pirate ship is a playful impossible premise, so pirate is not taught in a reliable normal context." },
  91: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "Dismissing postmodernism and anyone who calls it an ideology is a hostile academic-political claim, not a neutral context for ideology." },
  95: { decision: 'pass', categories: [], rationale: "Swapping an unspecified item for a new one is a common replacement instruction that clearly demonstrates swap." },
  97: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "A fictional Romance language and Welsh phonology require specialist linguistics background that overwhelms romance for a default learner." },
}
const severeIndices = new Set([64])
function rubricFor(decision: Decision, categories: string[]): Record<string, string> { const has = (names: string[]) => names.some((name) => categories.includes(name)); return { defaultLearningAppropriateness: decision === 'pass' ? 'YES' : 'NO', targetTeachingValue: has(['weak-teaching-value', 'rare-sense']) ? 'FAIL' : 'PASS', contextVocabularyLoad: has(['context-too-hard', 'specialist-background', 'proper-noun-heavy']) ? 'FAIL' : 'PASS', syntaxSimplicity: has(['syntax-too-complex', 'unnatural-English']) ? 'FAIL' : 'PASS', standaloneClarity: has(['context-dependent']) ? 'FAIL' : 'PASS', topicNeutrality: has(['political-heavy', 'medical-heavy', 'death-heavy', 'violence', 'extremism', 'hate', 'public-controversy', 'sexual', 'self-harm']) ? 'FAIL' : 'PASS', naturalModernEnglish: has(['unnatural-English', 'archaic', 'fantastical-context']) ? 'FAIL' : 'PASS', finalEditorDecision: decision === 'pass' ? 'PASS' : 'FAIL' } }
function flags(trace: Provenance): Record<string, number> { return Object.fromEntries(Object.entries(trace).filter(([, value]) => typeof value === 'number')) as Record<string, number> }
function csvCell(value: unknown): string { const text = typeof value === 'string' ? value : JSON.stringify(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }
const rows = candidates.rows.map((candidate, index) => { const trace = provenance[candidate.word]; const previous = priorByPair.get(`${candidate.word.toLocaleLowerCase()}::${candidate.sentenceId}`); const decision = previous?.decision === 'pass' ? previous : manual[index]; if (!trace || trace.sentenceId !== candidate.sentenceId) throw new Error(`Blind provenance mismatch at ${index}: ${candidate.word}|${candidate.sentenceId}`); if (!decision) throw new Error(`No blind decision at index ${index}: ${candidate.word}|${candidate.sentenceId}`); if (previous?.decision === 'reject') throw new Error(`Rejected prior blind pair re-entered: ${candidate.word}|${candidate.sentenceId}`); return { ...candidate, seed: candidates.seed, decision: decision.decision, categories: decision.categories, rationale: decision.rationale, reviewer: 'Lula-agent', reviewBasis: 'blind-sentence-read-semantic-rubric', semanticDecisionSource: 'sentence-read', rubric: rubricFor(decision.decision, decision.categories), machineFlags: flags(trace), severeInappropriate: severeIndices.has(index) } })
const rationales = rows.map((row) => row.rationale); const frequencies = new Map<string, number>(); for (const rationale of rationales) frequencies.set(rationale, (frequencies.get(rationale) ?? 0) + 1); const exactDuplicateRationaleCount = [...frequencies.values()].filter((count) => count > 1).reduce((total, count) => total + count - 1, 0); const genericRationaleCount = rationales.filter((rationale) => rationale.length < 60 || /^Read in full:/i.test(rationale) || /^This is complete and natural/i.test(rationale)).length; const passCount = rows.filter((row) => row.decision === 'pass').length; const failCount = rows.length - passCount; const severeCount = rows.filter((row) => row.severeInappropriate).length; const rationaleQuality = { reviewedRows: rows.length, exactDuplicateRationaleCount, genericRationaleCount, genericRationaleShare: Number((genericRationaleCount / rows.length).toFixed(4)), gate: exactDuplicateRationaleCount <= 5 && genericRationaleCount / rows.length < 0.05, method: 'Audit-only reviewer-quality QA; it never creates or changes semantic decisions.' }
await writeFile(resolve(auditRoot, 'blind-validation.json'), `${JSON.stringify({ round: 5, attempt: 4, seed: candidates.seed, rows, passCount, failCount, passRate: passCount / rows.length, severeInappropriateCount: severeCount, rationaleQuality, reviewMethod: 'Independent sentence-by-sentence blind semantic review; machine metrics were not shown before decisions.', noDecisionEditingForMetrics: true }, null, 2)}\n`, 'utf8')
const csvHeader = ['index', 'word', 'sentenceId', 'sentence', 'decision', 'categories', 'rationale', 'severeInappropriate']; const csv = [csvHeader.join(','), ...rows.map((row, index) => [index, row.word, row.sentenceId, row.sentence, row.decision, row.categories, row.rationale, row.severeInappropriate].map(csvCell).join(','))].join('\n') + '\n'; await writeFile(resolve(auditRoot, 'blind-validation.csv'), csv, 'utf8'); await writeFile(resolve(auditRoot, 'blind-validation-summary.md'), `# Round 5 Blind Validation Attempt 4\n\n- Reviewed: ${rows.length}\n- PASS: ${passCount}\n- FAIL: ${failCount}\n- PASS rate: ${(passCount / rows.length * 100).toFixed(1)}%\n- Severe inappropriate: ${severeCount}\n- Rationale exact duplicates: ${exactDuplicateRationaleCount}\n- Generic rationale share: ${(genericRationaleCount / rows.length * 100).toFixed(1)}%\n\nThis is a sentence-read result. Any FAIL is retained as a FAIL and must be durably rejected, followed by rebuild and retest; no decision was changed to improve the percentage.\n`, 'utf8')
console.log(`Round 5 blind review attempt 4 written: sample=${rows.length}, pass=${passCount}, fails=${failCount}, severe=${severeCount}, rationaleDuplicates=${exactDuplicateRationaleCount}, genericShare=${(genericRationaleCount / rows.length * 100).toFixed(1)}%`)
