import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

type Decision = 'pass' | 'reject'
interface Note { decision: Decision; categories: string[]; rationale: string }
interface Candidate { word: string; sentenceId: number; sentence: string; reviewType: string; semanticDecisionSource: string }
interface Provenance { sentenceId: number; source: string; qualityScore: number; [key: string]: number | string }
const root = resolve(import.meta.dirname, '..'); const auditRoot = resolve(root, 'audit/v1.3-context-final-semantic')
const candidates = JSON.parse(await readFile(resolve(auditRoot, 'blind-validation-candidates.json'), 'utf8')) as { seed: number; rows: Candidate[] }
const provenance = JSON.parse(await readFile(resolve(root, 'data-source/examples/example-provenance.json'), 'utf8')) as Record<string, Provenance>
const decisions: Record<number, Note> = {
  0: { decision: 'pass', categories: [], rationale: "Love transcending time and space is a familiar poetic use that clearly demonstrates transcend." },
  1: { decision: 'pass', categories: [], rationale: "Being unable to answer for legal reasons gives legal a direct formal-law meaning." },
  2: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "Forfeiting a right to care about freedom is an accusatory political judgment, so claim is not shown in a neutral useful context." },
  3: { decision: 'pass', categories: [], rationale: "Sprinkling chocolate chips on cookies is a concrete cooking instruction that clearly teaches sprinkle." },
  4: { decision: 'pass', categories: [], rationale: "Wondering whether people were born to have offspring gives offspring a clear family-and-reproduction meaning." },
  5: { decision: 'pass', categories: [], rationale: "An evening stroll in prepared royal gardens is a natural, concrete leisure context for stroll." },
  6: { decision: 'pass', categories: [], rationale: "Saying someone may be swamped gives swamp a common figurative meaning of being overwhelmed." },
  7: { decision: 'pass', categories: [], rationale: "A business no longer being profitable as the economy falters gives profitable a clear financial meaning." },
  8: { decision: 'pass', categories: [], rationale: "Everything being lost in confusion is a short, direct use that clearly demonstrates confusion." },
  9: { decision: 'pass', categories: [], rationale: "The sentence makes a neutral distinction between queer existence and sexualization, giving queer a clear identity-descriptive use." },
  10: { decision: 'pass', categories: [], rationale: "Buying a car at a forfeiture auction gives auction a concrete purchasing context." },
  11: { decision: 'reject', categories: ['public-controversy', 'hate', 'context-too-hard'], rationale: "The Nakba, Stalin, and ethnic removals invoke traumatic historical and political comparison, making ethnic unsuitable for a neutral default example." },
  12: { decision: 'pass', categories: [], rationale: "A jury-selection remark gives jury a clear court-process meaning, even though the speaker's aura claim is humorous." },
  13: { decision: 'pass', categories: [], rationale: "Ferns flanking creek banks gives flank a clear side-position meaning in a concrete landscape." },
  14: { decision: 'reject', categories: ['religious-heavy', 'public-controversy'], rationale: "Catholic national holidays and secular-country status place catholic in a religion-and-politics argument rather than a neutral descriptive context." },
  15: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "Time weaving its web is a poetic metaphor with no concrete referent, so web is not taught through a reliable standalone example." },
  16: { decision: 'pass', categories: [], rationale: "Saying no language is superior to another gives superior a clear comparison-and-status meaning." },
  17: { decision: 'reject', categories: ['medical-heavy', 'political-heavy'], rationale: "The availability of mental healthcare for the working poor under neoliberalism is a loaded policy claim, not a neutral context for available." },
  18: { decision: 'pass', categories: [], rationale: "A completed scientific fellowship leading to continued support gives fellowship a clear academic-program meaning." },
  19: { decision: 'pass', categories: [], rationale: "Partitioning a hard drive is a direct, modern computing instruction that clearly shows partition." },
  20: { decision: 'pass', categories: [], rationale: "Replacing a hydraulic cylinder identifies cylinder through a concrete machine-part context." },
  21: { decision: 'pass', categories: [], rationale: "Asking whether someone has a nickname is a simple, familiar personal-information question." },
  22: { decision: 'pass', categories: [], rationale: "The contrast between refuting a lie and telling one gives refute a direct argument meaning." },
  23: { decision: 'pass', categories: [], rationale: "A cheap flip phone is a concrete device example that makes flip immediately understandable." },
  24: { decision: 'pass', categories: [], rationale: "Watching a highlight reel gives reel a familiar edited-video meaning." },
  25: { decision: 'pass', categories: [], rationale: "Asking for help installing a program is an ordinary computer-use context that clearly teaches install." },
  26: { decision: 'reject', categories: ['medical-heavy', 'violence'], rationale: "Broken bones and a dislocated shoulder make fracture part of a multiple-injury report, which is unnecessarily medical and harm-focused for default learning." },
  27: { decision: 'pass', categories: [], rationale: "Managing an office budget carefully gives budget a clear workplace-finance meaning." },
  28: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Melody notation and accidentals require specialist music theory background that overwhelms the basic target melody." },
  29: { decision: 'reject', categories: ['sexual', 'hate', 'violence'], rationale: "A rape and ethnic blame for not wearing a veil is a severe sexual-violence and identity-harm context unsuitable for veil." },
  30: { decision: 'pass', categories: [], rationale: "A story entertaining and fascinating someone is a natural cause-and-effect use of fascinate." },
  31: { decision: 'pass', categories: [], rationale: "Wearing a mask until herd immunity is achieved gives mask a clear public-health object meaning without offering medical instructions." },
  32: { decision: 'pass', categories: [], rationale: "Having a crush on someone is a familiar relationship expression that clearly teaches crush." },
  33: { decision: 'pass', categories: [], rationale: "Contrasting a drunk man's words with a sober man's thoughts gives sober a clear not-intoxicated meaning." },
  34: { decision: 'pass', categories: [], rationale: "Escaping with one's reputation intact gives intact a clear undamaged-or-preserved meaning." },
  35: { decision: 'reject', categories: ['medical-heavy', 'context-dependent'], rationale: "Not having been sent back to a psychiatric ward is a sensitive personal mental-health history that is unsuitable as a default context for ward." },
  36: { decision: 'pass', categories: [], rationale: "Stray cats eating food left outside gives stray a clear unowned-animal meaning." },
  37: { decision: 'reject', categories: ['hate', 'sexual', 'public-controversy'], rationale: "The sentence spreads a sexual-abuse accusation about queer people, making project a severe identity-harm context." },
  38: { decision: 'pass', categories: [], rationale: "Dragging a joke out is a common idiom that directly demonstrates drag in an extended-duration sense." },
  39: { decision: 'pass', categories: [], rationale: "Nitrous oxide being inert at room temperature gives oxide a precise, accessible chemistry context." },
  40: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Ejective consonants and language geography require specialist phonetics knowledge that overwhelms occur." },
  41: { decision: 'reject', categories: ['archaic', 'context-dependent', 'weak-teaching-value'], rationale: "Casting aspersions on a witness's probity is a formal legal idiom with archaic vocabulary, so cast is not taught in a broadly useful context." },
  42: { decision: 'pass', categories: [], rationale: "Asking whether someone wants criticism or validation is a clear interpersonal communication context for criticism." },
  43: { decision: 'pass', categories: [], rationale: "Flattering the elephant while trampling the ant presents flatter as praising for advantage in a memorable but understandable contrast." },
  44: { decision: 'pass', categories: [], rationale: "Different levels of enthusiasm about a job give enthusiastic a clear attitude-toward-work meaning." },
  45: { decision: 'pass', categories: [], rationale: "A defendant being fit to stand trial is a direct legal-status context that clearly teaches defendant." },
  46: { decision: 'pass', categories: [], rationale: "The baseball idiom of being born on third base and thinking one hit a triple gives triple a clear sports meaning." },
  47: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "An intergalactic voyage is a science-fiction setting that does not provide a normal default context for humanity." },
  48: { decision: 'pass', categories: [], rationale: "Appreciating someone's enthusiasm for discovering new things is a natural, positive interpersonal use." },
  49: { decision: 'pass', categories: [], rationale: "Studying cartography for a fantasy book gives fantasy a clear literary-genre meaning in a creative context." },
  50: { decision: 'reject', categories: ['proper-noun-heavy', 'context-too-hard'], rationale: "The named Josephus and the question of an impartial historian require historical background that distracts from historian." },
  51: { decision: 'pass', categories: [], rationale: "Wishing someone flowers they desire gives desire a clear wanting-or-wishing meaning." },
  52: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "To hope is to be vulnerable is an abstract aphorism with no concrete situation, so vulnerable is not taught precisely enough." },
  53: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Shadow people spying from another dimension is a paranormal premise, so dimension is not grounded in a reliable default-learning context." },
  54: { decision: 'pass', categories: [], rationale: "Recording an instrumental album gives instrumental a clear music-without-vocals meaning." },
  55: { decision: 'pass', categories: [], rationale: "Volunteering to build houses for disaster survivors gives disaster a clear large-scale harmful-event context without graphic detail." },
  56: { decision: 'pass', categories: [], rationale: "A phone app helping diagnose potential field problems gives diagnose a clear identify-a-problem meaning without diagnosing a person." },
  57: { decision: 'pass', categories: [], rationale: "A surgeon reaching for a scalpel is a concise, recognizable medical-work context that clearly teaches surgeon." },
  58: { decision: 'pass', categories: [], rationale: "Contrasting speaking French with composing in it gives compose a clear writing-language meaning." },
  59: { decision: 'pass', categories: [], rationale: "A wallet crafted from one piece of walnut is a concrete object-material context for wallet." },
  60: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Fascists, liberals, and claims about people versus abstractions create a hostile political generalization unrelated to preference." },
  61: { decision: 'pass', categories: [], rationale: "Replacing a valve is a direct maintenance context that makes valve concrete." },
  62: { decision: 'pass', categories: [], rationale: "A new geologic epoch caused by human environmental damage gives epoch a clear geological-period meaning." },
  63: { decision: 'pass', categories: [], rationale: "Calling a friend an inspiration gives inspiration a familiar influence-and-motivation meaning." },
  64: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "The beauty of virtue being self-evident is an abstract moral assertion with no concrete situation to teach virtue." },
  65: { decision: 'pass', categories: [], rationale: "Nourishing a garden with rainwater gives nourish a clear support-growth meaning in an everyday setting." },
  66: { decision: 'pass', categories: [], rationale: "A vast array of websites gives array a clear collection-of-many-items meaning." },
  67: { decision: 'pass', categories: [], rationale: "A study suggesting optimism may lengthen life gives optimistic a clear hopeful-attitude meaning." },
  68: { decision: 'pass', categories: [], rationale: "Overcoming difficulties while quitting smoking gives overcome a clear successfully-deal-with meaning." },
  69: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "An identity crumbling is an abstract emotional metaphor with no concrete referent, so crumble is not taught as a reliable default example." },
  70: { decision: 'pass', categories: [], rationale: "Jumping over a counter to steal money gives counter a concrete shop-layout meaning." },
  71: { decision: 'pass', categories: [], rationale: "A starship prototype crashing during test launches gives prototype a clear early-model engineering meaning." },
  72: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "Exotic birds is vague travel-and-wildlife labeling without explaining what makes the birds exotic, so the target is weakly taught." },
  73: { decision: 'pass', categories: [], rationale: "Testing whether language detection works gives detection a direct technology function meaning." },
  74: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "Gender-affirming care and a claim about cis people place primary in a contested identity-medical policy context." },
  75: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "Finding a solution soon is a vague question with no problem or proposed answer, so solution lacks useful standalone teaching context." },
  76: { decision: 'pass', categories: [], rationale: "Reconciling contradictions is a direct reasoning use that clearly demonstrates reconcile." },
  77: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "A prisoner swap depends on conflict and political negotiation, making swap part of a charged context rather than an ordinary exchange." },
  78: { decision: 'reject', categories: ['medical-heavy', 'context-dependent'], rationale: "An impulse-control problem is a personal clinical label with no concrete action, so impulse is not suitable as a neutral default example." },
  79: { decision: 'pass', categories: [], rationale: "A court reaching a fair verdict is a complete legal decision context that clearly teaches verdict." },
  80: { decision: 'pass', categories: [], rationale: "An economic crisis affecting local businesses gives economic a clear finance-and-society modifier meaning." },
  81: { decision: 'pass', categories: [], rationale: "A database of voices used for speech recognition gives database a clear technology-storage meaning." },
  82: { decision: 'pass', categories: [], rationale: "Astronauts staying fit to avoid muscle loss gives avoid a clear prevention meaning in a concrete space-travel context." },
  83: { decision: 'pass', categories: [], rationale: "Calling a post worth a bump is a common online use that makes bump clear as renewed attention." },
  84: { decision: 'pass', categories: [], rationale: "Calling turquoise water the highlight of a vacation gives highlight a clear best-part meaning." },
  85: { decision: 'pass', categories: [], rationale: "A car being totaled in a crash while Tom is uninjured gives crash a clear accident meaning without graphic detail." },
  86: { decision: 'pass', categories: [], rationale: "Picking up a prescription for someone else gives prescription a common pharmacy context." },
  87: { decision: 'pass', categories: [], rationale: "Numerous technical difficulties on a mission gives numerous a clear many-in-number meaning." },
  88: { decision: 'reject', categories: ['unnatural-English', 'archaic', 'context-dependent'], rationale: "The sentence contains the obscure hase wording and an awkward grain-and-straw construction, so grain is not a reliable natural model." },
  89: { decision: 'pass', categories: [], rationale: "Negotiating better trade deals gives negotiate a clear bargaining meaning in a familiar public context." },
  90: { decision: 'pass', categories: [], rationale: "Knowing the truth as both gift and burden gives burden a clear difficult-responsibility meaning." },
  91: { decision: 'reject', categories: ['political-heavy', 'proper-noun-heavy'], rationale: "A named current political figure describing himself as conservative makes conservative depend on partisan identity and public-figure context." },
  92: { decision: 'pass', categories: [], rationale: "A slice of cake and a glass of eggnog provide a simple, concrete food-serving context." },
  93: { decision: 'pass', categories: [], rationale: "Venus being hot enough to melt lead gives melt a precise physical-change meaning." },
  94: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "A skeleton following someone everywhere is a spooky supernatural image, so skeleton is not presented in a normal useful context." },
  95: { decision: 'pass', categories: [], rationale: "Tenant farming and sharecropping give tenant a clear agricultural land-use meaning." },
  96: { decision: 'pass', categories: [], rationale: "Reviving dead languages gives revive a clear bring-back-to-use meaning in an understandable academic context." },
  97: { decision: 'pass', categories: [], rationale: "Sentences and opinions sometimes overlapping gives overlap a clear shared-area or coincidence meaning." },
  98: { decision: 'pass', categories: [], rationale: "Full mouths and unanimous head-bobbing give unanimous a clear everyone-agrees meaning." },
  99: { decision: 'pass', categories: [], rationale: "A plainclothes officer making an arrest is a direct law-enforcement context that clearly demonstrates arrest." },
}
const severeIndices = new Set([29, 37])
function rubricFor(decision: Decision, categories: string[]): Record<string, string> { const has = (names: string[]) => names.some((name) => categories.includes(name)); return { defaultLearningAppropriateness: decision === 'pass' ? 'YES' : 'NO', targetTeachingValue: has(['weak-teaching-value', 'rare-sense']) ? 'FAIL' : 'PASS', contextVocabularyLoad: has(['context-too-hard', 'specialist-background', 'proper-noun-heavy']) ? 'FAIL' : 'PASS', syntaxSimplicity: has(['syntax-too-complex', 'unnatural-English']) ? 'FAIL' : 'PASS', standaloneClarity: has(['context-dependent']) ? 'FAIL' : 'PASS', topicNeutrality: has(['political-heavy', 'medical-heavy', 'death-heavy', 'violence', 'extremism', 'hate', 'public-controversy', 'sexual', 'self-harm']) ? 'FAIL' : 'PASS', naturalModernEnglish: has(['unnatural-English', 'archaic', 'fantastical-context']) ? 'FAIL' : 'PASS', finalEditorDecision: decision === 'pass' ? 'PASS' : 'FAIL' } }
function flags(trace: Provenance): Record<string, number> { return Object.fromEntries(Object.entries(trace).filter(([, value]) => typeof value === 'number')) as Record<string, number> }
function csvCell(value: unknown): string { const text = typeof value === 'string' ? value : JSON.stringify(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }
const rows = candidates.rows.map((candidate, index) => { const trace = provenance[candidate.word]; const decision = decisions[index]; if (!trace || trace.sentenceId !== candidate.sentenceId) throw new Error(`Blind provenance mismatch at ${index}: ${candidate.word}|${candidate.sentenceId}`); if (!decision) throw new Error(`No blind decision at index ${index}: ${candidate.word}|${candidate.sentenceId}`); return { ...candidate, seed: candidates.seed, decision: decision.decision, categories: decision.categories, rationale: decision.rationale, reviewer: 'Lula-agent', reviewBasis: 'blind-sentence-read-semantic-rubric', semanticDecisionSource: 'sentence-read', rubric: rubricFor(decision.decision, decision.categories), machineFlags: flags(trace), severeInappropriate: severeIndices.has(index) } })
const rationales = rows.map((row) => row.rationale); const frequencies = new Map<string, number>(); for (const rationale of rationales) frequencies.set(rationale, (frequencies.get(rationale) ?? 0) + 1); const exactDuplicateRationaleCount = [...frequencies.values()].filter((count) => count > 1).reduce((total, count) => total + count - 1, 0); const genericRationaleCount = rationales.filter((rationale) => rationale.length < 60 || /^Read in full:/i.test(rationale) || /^This is complete and natural/i.test(rationale)).length; const passCount = rows.filter((row) => row.decision === 'pass').length; const failCount = rows.length - passCount; const severeCount = rows.filter((row) => row.severeInappropriate).length; const rationaleQuality = { reviewedRows: rows.length, exactDuplicateRationaleCount, genericRationaleCount, genericRationaleShare: Number((genericRationaleCount / rows.length).toFixed(4)), gate: exactDuplicateRationaleCount <= 5 && genericRationaleCount / rows.length < 0.05, method: 'Audit-only reviewer-quality QA; it never creates or changes semantic decisions.' }
await writeFile(resolve(auditRoot, 'blind-validation.json'), `${JSON.stringify({ round: 5, attempt: 2, seed: candidates.seed, rows, passCount, failCount, passRate: passCount / rows.length, severeInappropriateCount: severeCount, rationaleQuality, reviewMethod: 'Independent sentence-by-sentence blind semantic review; machine metrics were not shown before decisions.', noDecisionEditingForMetrics: true }, null, 2)}\n`, 'utf8')
const csvHeader = ['index', 'word', 'sentenceId', 'sentence', 'decision', 'categories', 'rationale', 'severeInappropriate']; const csv = [csvHeader.join(','), ...rows.map((row, index) => [index, row.word, row.sentenceId, row.sentence, row.decision, row.categories, row.rationale, row.severeInappropriate].map(csvCell).join(','))].join('\n') + '\n'; await writeFile(resolve(auditRoot, 'blind-validation.csv'), csv, 'utf8'); await writeFile(resolve(auditRoot, 'blind-validation-summary.md'), `# Round 5 Blind Validation Attempt 2\n\n- Reviewed: ${rows.length}\n- PASS: ${passCount}\n- FAIL: ${failCount}\n- PASS rate: ${(passCount / rows.length * 100).toFixed(1)}%\n- Severe inappropriate: ${severeCount}\n- Rationale exact duplicates: ${exactDuplicateRationaleCount}\n- Generic rationale share: ${(genericRationaleCount / rows.length * 100).toFixed(1)}%\n\nThis is a sentence-read result. Any FAIL is retained as a FAIL and must be durably rejected, followed by rebuild and retest; no decision was changed to improve the percentage.\n`, 'utf8')
console.log(`Round 5 blind review attempt 2 written: sample=${rows.length}, pass=${passCount}, fails=${failCount}, severe=${severeCount}, rationaleDuplicates=${exactDuplicateRationaleCount}, genericShare=${(genericRationaleCount / rows.length * 100).toFixed(1)}%`)
