import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

type Decision = 'pass' | 'reject'
interface Note { decision: Decision; categories: string[]; rationale: string }
interface Candidate { word: string; sentenceId: number; sentence: string; reviewType: string; semanticDecisionSource: string }
interface Provenance { sentenceId: number; source: string; qualityScore: number; [key: string]: number | string }
interface PriorRow extends Candidate, Note { [key: string]: unknown }
const root = resolve(import.meta.dirname, '..'); const auditRoot = resolve(root, 'audit/v1.3-context-final-semantic')
const candidates = JSON.parse(await readFile(resolve(auditRoot, 'blind-validation-candidates.json'), 'utf8')) as { seed: number; rows: Candidate[] }
const provenance = JSON.parse(await readFile(resolve(root, 'data-source/examples/example-provenance.json'), 'utf8')) as Record<string, Provenance>
const priorRows = (await Promise.all([1, 2].map(async (attempt) => JSON.parse(await readFile(resolve(auditRoot, `blind-validation-attempt-${attempt}.json`), 'utf8')).rows as PriorRow[]))).flat()
const priorByPair = new Map(priorRows.map((row) => [`${row.word.toLocaleLowerCase()}::${row.sentenceId}`, row]))
const manual: Record<number, Note> = {
  3: { decision: 'pass', categories: [], rationale: "An overhead compartment holding a duffel bag gives compartment a clear travel-storage meaning." },
  4: { decision: 'pass', categories: [], rationale: "Opening a door with a grin gives grin a direct, visible-expression meaning." },
  6: { decision: 'pass', categories: [], rationale: "A band's final album receiving universal acclaim gives album a clear music-release meaning." },
  7: { decision: 'pass', categories: [], rationale: "Describing Judaism as an ethnic religion gives ethnic a clear group-and-identity modifier meaning in a concise sentence." },
  8: { decision: 'pass', categories: [], rationale: "Getting back in the groove of things is a familiar idiom for returning to a routine." },
  9: { decision: 'pass', categories: [], rationale: "Journalists' right to access and disseminate information gives access a clear permission-to-reach-information meaning." },
  10: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "GamerGate, reactionaries, and cancel-culture claims create a niche hostile controversy that is unsuitable as a neutral context for cancel." },
  11: { decision: 'pass', categories: [], rationale: "Turning failures into fuel for growth gives fuel a clear figurative source-of-motivation meaning." },
  15: { decision: 'pass', categories: [], rationale: "Worrying about how to implement an interesting idea gives implement a direct project-execution meaning." },
  19: { decision: 'pass', categories: [], rationale: "A filmmaker entertaining an audience while making it think gives audience a clear group-of-viewers meaning." },
  24: { decision: 'pass', categories: [], rationale: "Data security being the armor of modern life gives armor a clear protective metaphor tied to a familiar concept." },
  26: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Anarchists and mutual aid introduce a political ideology claim, so function is not shown in a neutral default context." },
  30: { decision: 'pass', categories: [], rationale: "A vast array of websites gives vast a clear very-large-in-size or amount meaning." },
  34: { decision: 'pass', categories: [], rationale: "Asking why something must be represented as a string gives represent a clear technical-form meaning." },
  39: { decision: 'pass', categories: [], rationale: "Testimony casting serious doubt on an account is a familiar legal idiom that clearly demonstrates cast's causal use." },
  41: { decision: 'pass', categories: [], rationale: "Asking how to get protein is a short, familiar nutrition question with the target unmistakable." },
  46: { decision: 'reject', categories: ['religious-heavy', 'fantastical-context'], rationale: "A predicted rapture occurring in exactly three years is an apocalyptic religious claim, not a neutral context for occur." },
  51: { decision: 'pass', categories: [], rationale: "Foster care and potential adopters give foster a clear child-care placement meaning in a factual social sentence." },
  53: { decision: 'pass', categories: [], rationale: "The cosmic web is a recognizable astronomy concept that gives web a clear large-scale structure meaning." },
  54: { decision: 'pass', categories: [], rationale: "An island economy relying on external trade gives external a clear outside-source meaning." },
  59: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "A dictator's appointee rolling back protections frames vulnerable populations inside a charged political accusation rather than a neutral context." },
  61: { decision: 'pass', categories: [], rationale: "Getting out of a car to assess damage is a complete, ordinary inspection context for assess." },
  63: { decision: 'reject', categories: ['political-heavy', 'violence'], rationale: "Resistance and a fight for independence make independence depend on a conflict narrative instead of a neutral self-governance context." },
  67: { decision: 'pass', categories: [], rationale: "A dietitian observing clients shed pounds gives shed a clear lose-weight meaning in a non-prescriptive report." },
  68: { decision: 'pass', categories: [], rationale: "Fixing a broken light fixture gives fixture a concrete household-object meaning." },
  69: { decision: 'pass', categories: [], rationale: "Treaty ratification by all parties is a clear formal-agreement context that directly demonstrates treaty." },
  71: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Finding a portal to another dimension is a fantasy premise, so dimension is not anchored in a normal default-learning context." },
  74: { decision: 'pass', categories: [], rationale: "An ingredient being prominent in an omelette's composition gives prominent a clear most-noticeable-or-important meaning." },
  80: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "A skeleton dog chasing Cookie is a spooky fantasy image that does not provide a normal useful context for skeleton." },
  82: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "Could this be the solution we need supplies no problem or candidate answer, so solution is left as an unexplained abstract label." },
  83: { decision: 'pass', categories: [], rationale: "Young Tom hating old Tom and vice versa gives vice versa a clear reversed-relation meaning." },
  85: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Being born on a pirate ship is a playful fantastical claim that does not give pirate a reliable default-learning context." },
  88: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "A steadfast Korea-U.S. alliance and relationship with China place alliance in a current geopolitical context that is too charged for the default pool." },
  89: { decision: 'reject', categories: ['unnatural-English', 'archaic', 'context-dependent'], rationale: "The obscure hase word and awkward grain-and-straw wording make this an unreliable natural-English sentence for grain." },
  90: { decision: 'reject', categories: ['medical-heavy', 'context-dependent'], rationale: "Being sent to a psychiatric ward thirteen times is a sensitive personal mental-health history, not a neutral default context for ward." },
  94: { decision: 'pass', categories: [], rationale: "A primary school teacher gives primary a clear education-level meaning in a simple family description." },
  98: { decision: 'reject', categories: ['death-heavy', 'weak-teaching-value'], rationale: "The identical-graves joke is morbid and distracting, so cemetery is not taught through a neutral default context." },
  99: { decision: 'pass', categories: [], rationale: "Driving off a cliff gives cliff a direct physical-landform meaning in a short, non-graphic accident sentence." },
}
function rubricFor(decision: Decision, categories: string[]): Record<string, string> { const has = (names: string[]) => names.some((name) => categories.includes(name)); return { defaultLearningAppropriateness: decision === 'pass' ? 'YES' : 'NO', targetTeachingValue: has(['weak-teaching-value', 'rare-sense']) ? 'FAIL' : 'PASS', contextVocabularyLoad: has(['context-too-hard', 'specialist-background', 'proper-noun-heavy']) ? 'FAIL' : 'PASS', syntaxSimplicity: has(['syntax-too-complex', 'unnatural-English']) ? 'FAIL' : 'PASS', standaloneClarity: has(['context-dependent']) ? 'FAIL' : 'PASS', topicNeutrality: has(['political-heavy', 'medical-heavy', 'death-heavy', 'violence', 'extremism', 'hate', 'public-controversy', 'sexual', 'self-harm']) ? 'FAIL' : 'PASS', naturalModernEnglish: has(['unnatural-English', 'archaic', 'fantastical-context']) ? 'FAIL' : 'PASS', finalEditorDecision: decision === 'pass' ? 'PASS' : 'FAIL' } }
function flags(trace: Provenance): Record<string, number> { return Object.fromEntries(Object.entries(trace).filter(([, value]) => typeof value === 'number')) as Record<string, number> }
function csvCell(value: unknown): string { const text = typeof value === 'string' ? value : JSON.stringify(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }
const rows = candidates.rows.map((candidate, index) => { const trace = provenance[candidate.word]; const previous = priorByPair.get(`${candidate.word.toLocaleLowerCase()}::${candidate.sentenceId}`); const decision = previous?.decision === 'pass' ? previous : manual[index]; if (!trace || trace.sentenceId !== candidate.sentenceId) throw new Error(`Blind provenance mismatch at ${index}: ${candidate.word}|${candidate.sentenceId}`); if (!decision) throw new Error(`No blind decision at index ${index}: ${candidate.word}|${candidate.sentenceId}`); if (previous?.decision === 'reject') throw new Error(`Rejected prior blind pair re-entered: ${candidate.word}|${candidate.sentenceId}`); return { ...candidate, seed: candidates.seed, decision: decision.decision, categories: decision.categories, rationale: decision.rationale, reviewer: 'Lula-agent', reviewBasis: 'blind-sentence-read-semantic-rubric', semanticDecisionSource: 'sentence-read', rubric: rubricFor(decision.decision, decision.categories), machineFlags: flags(trace), severeInappropriate: false } })
const rationales = rows.map((row) => row.rationale); const frequencies = new Map<string, number>(); for (const rationale of rationales) frequencies.set(rationale, (frequencies.get(rationale) ?? 0) + 1); const exactDuplicateRationaleCount = [...frequencies.values()].filter((count) => count > 1).reduce((total, count) => total + count - 1, 0); const genericRationaleCount = rationales.filter((rationale) => rationale.length < 60 || /^Read in full:/i.test(rationale) || /^This is complete and natural/i.test(rationale)).length; const passCount = rows.filter((row) => row.decision === 'pass').length; const failCount = rows.length - passCount; const severeCount = rows.filter((row) => row.severeInappropriate).length; const rationaleQuality = { reviewedRows: rows.length, exactDuplicateRationaleCount, genericRationaleCount, genericRationaleShare: Number((genericRationaleCount / rows.length).toFixed(4)), gate: exactDuplicateRationaleCount <= 5 && genericRationaleCount / rows.length < 0.05, method: 'Audit-only reviewer-quality QA; it never creates or changes semantic decisions.' }
await writeFile(resolve(auditRoot, 'blind-validation.json'), `${JSON.stringify({ round: 5, attempt: 3, seed: candidates.seed, rows, passCount, failCount, passRate: passCount / rows.length, severeInappropriateCount: severeCount, rationaleQuality, reviewMethod: 'Independent sentence-by-sentence blind semantic review; machine metrics were not shown before decisions.', noDecisionEditingForMetrics: true }, null, 2)}\n`, 'utf8')
const csvHeader = ['index', 'word', 'sentenceId', 'sentence', 'decision', 'categories', 'rationale', 'severeInappropriate']; const csv = [csvHeader.join(','), ...rows.map((row, index) => [index, row.word, row.sentenceId, row.sentence, row.decision, row.categories, row.rationale, row.severeInappropriate].map(csvCell).join(','))].join('\n') + '\n'; await writeFile(resolve(auditRoot, 'blind-validation.csv'), csv, 'utf8'); await writeFile(resolve(auditRoot, 'blind-validation-summary.md'), `# Round 5 Blind Validation Attempt 3\n\n- Reviewed: ${rows.length}\n- PASS: ${passCount}\n- FAIL: ${failCount}\n- PASS rate: ${(passCount / rows.length * 100).toFixed(1)}%\n- Severe inappropriate: ${severeCount}\n- Rationale exact duplicates: ${exactDuplicateRationaleCount}\n- Generic rationale share: ${(genericRationaleCount / rows.length * 100).toFixed(1)}%\n\nThis is a sentence-read result. Any FAIL is retained as a FAIL and must be durably rejected, followed by rebuild and retest; no decision was changed to improve the percentage.\n`, 'utf8')
console.log(`Round 5 blind review attempt 3 written: sample=${rows.length}, pass=${passCount}, fails=${failCount}, severe=${severeCount}, rationaleDuplicates=${exactDuplicateRationaleCount}, genericShare=${(genericRationaleCount / rows.length * 100).toFixed(1)}%`)
