import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

type Decision = 'pass' | 'reject'
interface ManualDecision { decision: Decision; categories: string[]; rationale: string }
interface Candidate { word: string; sentenceId: number; sentence: string; reviewType: string; semanticDecisionSource: string; selectionSource?: string }
interface Provenance { sentenceId: number; source: string; qualityScore: number; [key: string]: number | string }

const root = resolve(import.meta.dirname, '..')
const auditRoot = resolve(root, 'audit/v1.3-context-final-semantic')
const phaseAPath = resolve(auditRoot, 'phase-a-candidates.json')
const mandatoryPath = resolve(auditRoot, 'mandatory-recheck-candidates.json')
const provenancePath = resolve(root, 'data-source/examples/example-provenance.json')

const phaseADecisions: Record<number, ManualDecision> = {
  0: { decision: 'reject', categories: ['context-too-hard'], rationale: "For project, the uncommon adjective putative is harder than the target and makes the intended sentence meaning less accessible." },
  1: { decision: 'pass', categories: [], rationale: "The loan and credit-card debt give credit a familiar financial meaning without requiring specialist background." },
  2: { decision: 'pass', categories: [], rationale: "Spacecraft, miles, and planets provide a clear concrete setting for explore." },
  3: { decision: 'pass', categories: [], rationale: "The direct question links climate to a familiar everyday issue, climate change, and keeps the target central." },
  4: { decision: 'pass', categories: [], rationale: "A missed sales quota is a short, ordinary workplace situation that makes quota immediately clear." },
  5: { decision: 'pass', categories: [], rationale: "The pinky-swear agreement shows solemn as serious in a playful but understandable everyday contrast." },
  6: { decision: 'pass', categories: [], rationale: "Garbage cans make the noun concrete, and the sentence is grammatically direct despite its unpleasant situation." },
  7: { decision: 'pass', categories: [], rationale: "Wide-eyed optimism is the cause of the speaker's irritation, clearly showing optimism as an attitude." },
  8: { decision: 'pass', categories: [], rationale: "Generating electricity from sewage gives generate a concrete production meaning; the scientific setting remains understandable." },
  9: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "The contrast between science and faith is an abstract slogan, and faith brings them together does not give a precise or natural teaching context." },
  10: { decision: 'pass', categories: [], rationale: "The comparison of alliteration and end rhyme places poetry in a clear literary form; the sentence is a complete modern explanation." },
  11: { decision: 'pass', categories: [], rationale: "Describing a room from memory demonstrates detail in its ordinary meaning of specific information." },
  12: { decision: 'reject', categories: ['other'], rationale: "The target assume is understandable, but road rage and the profanity add unnecessary hostile emotional load to a default learning example." },
  13: { decision: 'pass', categories: [], rationale: "A daily skincare routine and a moment of peace give routine a clear, contemporary habit context." },
  14: { decision: 'reject', categories: ['religious-heavy', 'weak-teaching-value'], rationale: "The spiritual claim that all things are unified is vague and belief-dependent, so it supplies little concrete teaching value for unity." },
  15: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "The wording about a strand going with the other is awkward and leaves the intended meaning of strand unclear." },
  16: { decision: 'reject', categories: ['political-heavy', 'context-too-hard', 'public-controversy'], rationale: "The phrase cis ideology makes impose depend on a sensitive culture-war claim and specialist identity vocabulary unrelated to basic verb teaching." },
  17: { decision: 'pass', categories: [], rationale: "The question about intelligent life uses intelligent in a familiar contrast with ordinary life and keeps the sentence self-contained." },
  18: { decision: 'pass', categories: [], rationale: "Personifying a painful knee as betraying the speaker is a natural figurative use that clearly shows betray." },
  19: { decision: 'reject', categories: ['political-heavy', 'medical-heavy'], rationale: "The sentence makes exploit depend on a contentious drug-prohibition argument and addiction-policy background rather than a neutral example." },
  20: { decision: 'pass', categories: [], rationale: "A trusted volunteer at a childcare center gives volunteer a normal civic role with simple surrounding vocabulary." },
  21: { decision: 'pass', categories: [], rationale: "A country with rich culture and history is a straightforward, neutral setting for diverse." },
  22: { decision: 'pass', categories: [], rationale: "Patient advocate and mental health conditions show mental in a common social-health collocation without technical detail." },
  23: { decision: 'pass', categories: [], rationale: "Going to a remote area and looking at the sky gives remote a concrete, standalone location contrast." },
  24: { decision: 'reject', categories: ['extremism', 'hate'], rationale: "Swastika flags introduce extremist imagery and historical hate into an example whose target appropriate does not need that burden." },
  25: { decision: 'pass', categories: [], rationale: "Conducting a cybersecurity audit is a clear modern example of conduct meaning carry out, and the sentence is a complete question." },
  26: { decision: 'pass', categories: [], rationale: "Interpreting a remark literally demonstrates the target contrast with figurative meaning in a self-contained sentence." },
  27: { decision: 'pass', categories: [], rationale: "Overwriting previously saved data is a common, concrete use of previous with no extra background." },
  28: { decision: 'pass', categories: [], rationale: "Tossing a log onto a fire is an ordinary physical action that makes the target immediately understandable." },
  29: { decision: 'pass', categories: [], rationale: "Untold wealth and glory provides a familiar narrative phrase in which wealth is the central noun." },
  30: { decision: 'pass', categories: [], rationale: "A person's perspective is directly contrasted with how unfashionable it may seem, making the target's viewpoint meaning clear." },
  31: { decision: 'pass', categories: [], rationale: "The whale example explicitly contrasts a stereotype with an exception and remains understandable despite the naturalist aside." },
  32: { decision: 'pass', categories: [], rationale: "The phrase potential in every challenge shows the target as a possible quality or opportunity in ordinary language." },
  33: { decision: 'reject', categories: ['violence', 'political-heavy'], rationale: "Crushing separatists frames the target in violent political conflict, adding unnecessary ideological background to a common verb." },
  34: { decision: 'pass', categories: [], rationale: "Love as a powerful force is an accessible metaphor that clearly illustrates force as an influence." },
  35: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Blaming immigrants and a millionaire's reaction makes millionaire part of a loaded political and class satire rather than a neutral example." },
  36: { decision: 'pass', categories: [], rationale: "The question about doing something productive is everyday self-management language with the target used naturally." },
  37: { decision: 'reject', categories: ['death-heavy', 'context-dependent'], rationale: "A donation in lieu of flowers assumes an obituary or funeral context, adding death-related background not needed to teach donation." },
  38: { decision: 'pass', categories: [], rationale: "A dark theme in a menu is a concrete modern interface use that makes theme easy to understand." },
  39: { decision: 'pass', categories: [], rationale: "A hacked account and changed password give account a familiar, self-contained digital meaning." },
  40: { decision: 'pass', categories: [], rationale: "Space travel taking a toll on the body shows toll as a cost or harmful effect in a clear metaphor." },
  41: { decision: 'pass', categories: [], rationale: "The playful potato comparison still places universe in a complete, memorable sentence and does not require outside context." },
  42: { decision: 'pass', categories: [], rationale: "Astronaut suits and survival in space give survive a concrete cause-and-effect setting." },
  43: { decision: 'pass', categories: [], rationale: "An obscene gesture is a common, concise example of obscene without graphic detail." },
  44: { decision: 'pass', categories: [], rationale: "A mountain cabin with a valley view is a simple, vivid setting that makes cabin clear." },
  45: { decision: 'pass', categories: [], rationale: "A quake's aftermath and an unprecedented rupture give rupture a concrete scientific meaning that remains readable." },
  46: { decision: 'reject', categories: ['political-heavy', 'public-controversy', 'context-too-hard'], rationale: "Gender roles, authoritarian regimes, and inviolable add political and specialist load that is disproportionate to teaching fundamental." },
  47: { decision: 'pass', categories: [], rationale: "Being in charge around here is a common idiom that directly demonstrates charge as responsibility or control." },
  48: { decision: 'pass', categories: [], rationale: "The two short clauses show distort as deliberately changing facts, a clear and memorable verb use." },
  49: { decision: 'reject', categories: ['context-too-hard', 'other'], rationale: "Goblin mode is niche internet slang, so the sentence makes the ordinary target constant depend on cultural knowledge that a default learner may not have." },
  50: { decision: 'pass', categories: [], rationale: "A rating going down is a direct, everyday example of rating as an evaluation." },
  51: { decision: 'pass', categories: [], rationale: "A hypothetical warning label invites a clear label description and uses the target in a familiar object context." },
  52: { decision: 'pass', categories: [], rationale: "The sentence directly identifies a spouse and uses a complete family relationship context without extra background." },
  53: { decision: 'pass', categories: [], rationale: "Parents not approving of a lifestyle shows approve in a natural interpersonal judgment without specifying a sensitive group." },
  54: { decision: 'pass', categories: [], rationale: "A film's twist ending is a familiar storytelling context, and the idiom reinforces that twist was predictable." },
  55: { decision: 'pass', categories: [], rationale: "Lost sleep having a cumulative effect gives cumulative a clear additive meaning in an ordinary health context." },
  56: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "The collocation accomplish his job is unnatural, so the sentence does not model the target accomplish accurately." },
  57: { decision: 'pass', categories: [], rationale: "A mission reaching a conflict zone makes conflict a concrete noun for an area of disagreement or danger, with simple syntax." },
  58: { decision: 'pass', categories: [], rationale: "Photos of varied terrain on a planet give terrain a concrete landscape meaning; the science setting is understandable." },
  59: { decision: 'pass', categories: [], rationale: "A cybersecurity breach affecting a network is a concise modern example that clearly shows breach as unauthorized access." },
  60: { decision: 'pass', categories: [], rationale: "Arguing with people online is an ordinary, self-contained use of argue." },
  61: { decision: 'reject', categories: ['context-too-hard', 'specialist-background'], rationale: "Corporate bonds and especially a gilt introduce specialist finance vocabulary that is harder than invest and unnecessary for its basic meaning." },
  62: { decision: 'pass', categories: [], rationale: "The sewage-and-bacteria example describes generating electricity in a clear cause-and-effect sentence; both the action and result are understandable." },
  63: { decision: 'pass', categories: [], rationale: "Liquorice and the chalkboard comparison make equivalent visible as a similar sensory effect, despite the informal simile." },
  64: { decision: 'pass', categories: [], rationale: "No longer eligible for a prize is a common, direct condition that clearly defines eligible." },
  65: { decision: 'pass', categories: [], rationale: "Trust being fragile in a world of betrayal gives fragile a familiar metaphorical meaning with simple syntax." },
  66: { decision: 'pass', categories: [], rationale: "Continuity errors ruining a show's experience clearly illustrates ruin as damaging an outcome." },
  67: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "Reactionaries and queer children place queer in a current identity conflict with unnecessary ideological and emotional load." },
  68: { decision: 'pass', categories: [], rationale: "Embarking on a lifelong journey is a natural, readable phrase that directly shows embark as beginning a trip." },
  69: { decision: 'pass', categories: [], rationale: "A yacht attacked by an orca supplies a clear object-and-event context for yacht without graphic detail." },
  70: { decision: 'pass', categories: [], rationale: "A crisis pushing someone to the brink of despair gives brink a clear boundary metaphor and remains self-contained." },
  71: { decision: 'pass', categories: [], rationale: "The moon's position between Earth and the sun is a precise, accessible explanation of eclipse." },
  72: { decision: 'pass', categories: [], rationale: "Asking someone to expand on an earlier point is a common conversational use of the target." },
  73: { decision: 'pass', categories: [], rationale: "The camera-recorded attack is a short, direct event context that makes attack unambiguous." },
  74: { decision: 'reject', categories: ['specialist-background', 'fantastical-context'], rationale: "Graphene and a space elevator require specialist or speculative science background that overwhelms the simple target cable." },
  75: { decision: 'pass', categories: [], rationale: "Not being at liberty to disclose mission details is a natural collocation and clearly demonstrates disclose." },
  76: { decision: 'pass', categories: [], rationale: "A debt someone owes is an ordinary financial relationship that makes owe clear." },
  77: { decision: 'pass', categories: [], rationale: "The question about remaining infectious after a viral infection is a simple health use with the target central." },
  78: { decision: 'reject', categories: ['context-too-hard', 'religious-heavy'], rationale: "Augury and divination are obscure terms, so the bird-behavior sentence makes behavior depend on specialist religious background." },
  79: { decision: 'pass', categories: [], rationale: "Joining an emergency response team gives response a familiar organizational meaning in a complete sentence." },
  80: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Quantitative verse in Latin poetry is a specialist literary topic, and the surrounding terminology is harder than quantitative." },
  81: { decision: 'pass', categories: [], rationale: "A space station orbiting Earth is a concrete, familiar setting that makes orbit clear." },
  82: { decision: 'pass', categories: [], rationale: "A faculty advisor is a common university role and gives faculty a straightforward institutional meaning." },
  83: { decision: 'pass', categories: [], rationale: "A supplementary dose after six months is a concise, understandable example of something added to a main dose." },
  84: { decision: 'pass', categories: [], rationale: "Providing first aid to injured civilians shows aid as help in a direct emergency context; the target meaning is not obscured." },
  85: { decision: 'pass', categories: [], rationale: "Combating climate change gives combat a clear figurative meaning of actively fighting a problem." },
  86: { decision: 'pass', categories: [], rationale: "Alcohol burning off in food is an ordinary cooking question with the target used naturally." },
  87: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Assigning a string to an integer variable requires programming type knowledge that is much harder than the target assign." },
  88: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "The niche word fursona and the click-through commission request make this a specialized online context with weak default teaching value." },
  89: { decision: 'pass', categories: [], rationale: "Kindness is named as a personal trait, giving trait a simple and familiar definition." },
  90: { decision: 'reject', categories: ['unnatural-English', 'fantastical-context', 'weak-teaching-value'], rationale: "A talking pillow promising not to bring compatible people together is absurd and does not model a natural use of compatible." },
  91: { decision: 'reject', categories: ['context-too-hard', 'public-controversy'], rationale: "Cisgenderism is specialist identity vocabulary tied to a charged debate, adding unnecessary load to teaching critic." },
  92: { decision: 'reject', categories: ['violence', 'political-heavy'], rationale: "Throwing food at people frames protest through harassment and confrontation rather than a neutral, standalone civic example." },
  93: { decision: 'pass', categories: [], rationale: "The speaker's certainty about what was seen makes convince clear as changing someone's belief." },
  94: { decision: 'pass', categories: [], rationale: "Smashing boiled pumpkin while cooking is a concrete, everyday verb use." },
  95: { decision: 'pass', categories: [], rationale: "Insisting on being right is a common interpersonal situation that clearly shows insist." },
  96: { decision: 'pass', categories: [], rationale: "Landing on an alien planet gives alien a clear contrast with familiar Earth life in a readable science-fiction setting." },
  97: { decision: 'pass', categories: [], rationale: "Confirm or deny claims is a standard phrase that directly demonstrates confirm." },
  98: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Evolutionary psychology and its scientific status require academic background that is harder than conception and distracts from the target." },
  99: { decision: 'pass', categories: [], rationale: "Pledging allegiance to a flag is a recognizable civic phrase that clearly shows pledge as a promise or commitment." },
  100: { decision: 'pass', categories: [], rationale: "Defining a project's scope by a deadline is a common teamwork example with both targets used plainly." },
  101: { decision: 'pass', categories: [], rationale: "A touchscreen monitor and a cat make monitor a concrete object in a light, self-contained sentence." },
  102: { decision: 'pass', categories: [], rationale: "The question about time being an illusion gives illusion a familiar abstract meaning without requiring a prior story." },
  103: { decision: 'reject', categories: ['context-too-hard', 'archaic'], rationale: "Appellation is an uncommon literary word and the marriage sentence makes magnificent secondary to a difficult historical title." },
  104: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "The claim about the political right dictating every aspect of life is a current ideological argument, not a neutral context for aspect." },
  105: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "Porcupine quills and punching holes are unusually specific craft details, while the sentence gives linen little ordinary teaching context." },
  106: { decision: 'pass', categories: [], rationale: "Recovery from a global recession is a familiar economic context that makes economy clear." },
  107: { decision: 'reject', categories: ['context-too-hard', 'unnatural-English'], rationale: "Took the mickey is a region-specific idiom, so the sentence makes reaction depend on cultural knowledge unrelated to the target." },
  108: { decision: 'pass', categories: [], rationale: "A logical explanation is a common phrase that gives logical a clear, standalone use." },
  109: { decision: 'pass', categories: [], rationale: "Supplementing income is an ordinary financial use that clearly shows adding to an existing amount." },
  110: { decision: 'pass', categories: [], rationale: "Exploring the cultural heritage of an island gives heritage a clear social and historical meaning." },
  111: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "The accusation about becoming a monster leaves the referent and situation unresolved, so claim is not taught in a clear standalone context." },
  112: { decision: 'pass', categories: [], rationale: "A significant scientific breakthrough is a familiar academic collocation that directly illustrates significant." },
  113: { decision: 'pass', categories: [], rationale: "The sentence uses species in a clear comparison between humans and other possible users of the Internet." },
  114: { decision: 'pass', categories: [], rationale: "Moody temperament leading to blunt remarks gives temperament a direct personality meaning." },
  115: { decision: 'pass', categories: [], rationale: "The team defining a project's scope by Monday is a complete, practical example of define." },
  116: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "Vignettes is a literary term harder than series, and the sentence provides little accessible reason for the target beyond a book label." },
  117: { decision: 'pass', categories: [], rationale: "A pool and deck overlooking a pasture show overlook as a direct spatial relationship." },
  118: { decision: 'reject', categories: ['political-heavy', 'weak-teaching-value'], rationale: "The claim that a society allowing poverty hates children is an ideological moral judgment that overloads poverty with an unnecessary argument." },
  119: { decision: 'pass', categories: [], rationale: "The writer's sentences not reflecting personal thoughts gives reflect a clear figurative correspondence meaning." },
  120: { decision: 'pass', categories: [], rationale: "Being a consumer of mental health services is a neutral service-user context that directly demonstrates consumer." },
  121: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Corrupt politicians and leftists turn corrupt into a partisan political accusation that is not needed for its ordinary meaning." },
  122: { decision: 'pass', categories: [], rationale: "The flat-Earth cat joke still gives flat a clear geometric meaning in a short, memorable sentence." },
  123: { decision: 'pass', categories: [], rationale: "A critical emergency on a space mission shows critical as urgent and important in an accessible context." },
  124: { decision: 'pass', categories: [], rationale: "Earth as the only known life-supporting planet gives planet a clear scientific meaning with familiar words." },
  125: { decision: 'pass', categories: [], rationale: "Someone being at a conference and inviting coffee is a simple social setting that makes conference clear." },
  126: { decision: 'pass', categories: [], rationale: "A paper clip holding paper is a concrete, everyday example of clip as an object." },
  127: { decision: 'reject', categories: ['context-dependent', 'unnatural-English'], rationale: "Beginning with But and comparing dreams with tiny surroundings leaves missing context, while the literary simile weakens gigantic's teaching clarity." },
  128: { decision: 'pass', categories: [], rationale: "The question contrasts shaping destiny with fate, giving destiny a clear common abstract meaning." },
  129: { decision: 'reject', categories: ['context-too-hard', 'political-heavy'], rationale: "Microcosm and a larger cultural debate create abstract media-analysis load that is harder than debate." },
  130: { decision: 'pass', categories: [], rationale: "Making a racket is an ordinary noisy-behavior use with a clear playful warning." },
  131: { decision: 'pass', categories: [], rationale: "A missed work alarm is a familiar everyday situation that directly illustrates alarm." },
  132: { decision: 'pass', categories: [], rationale: "Refreshing a page after an error is a clear modern interface use of refresh." },
  133: { decision: 'pass', categories: [], rationale: "Asking about a kitchen appliance is an ordinary household context that makes appliance concrete." },
  134: { decision: 'reject', categories: ['political-heavy', 'public-controversy', 'context-too-hard'], rationale: "Cis ideology is specialist and politically charged identity language, so it is not a neutral default context for ideology." },
  135: { decision: 'pass', categories: [], rationale: "The majority of emigrants continuing a journey provides a clear numerical contrast in a complete historical sentence." },
  136: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Power structures, corrupt politicians, and leftists make intact part of a partisan political claim rather than a neutral example." },
  137: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Disinformation and rebuttal place volume inside a current information-war debate with unnecessary political load." },
  138: { decision: 'pass', categories: [], rationale: "An untold story gives agony a clear emotional context and the sentence is a complete modern aphorism." },
  139: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Deep vein thrombosis is a serious specialist medical condition, and the pregnancy context overwhelms the basic target vein." },
  140: { decision: 'pass', categories: [], rationale: "People explaining a dispute and arranging a compromise gives arrange a clear cooperative action." },
  141: { decision: 'pass', categories: [], rationale: "A pool and deck overlooking pasture provide a clear, concrete use of pasture." },
  142: { decision: 'pass', categories: [], rationale: "A volunteer emergency relief team shows emergency in a familiar public-help setting without specialist detail." },
  143: { decision: 'pass', categories: [], rationale: "The common idiom if push comes to shove provides a natural, readable use of shove in a self-contained family situation." },
  144: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Anaerobic respiration and fermentation are paired technical biology terms, making distinct depend on specialist knowledge." },
  145: { decision: 'pass', categories: [], rationale: "Cats exhibiting a fur pattern gives exhibit a direct, observable meaning with ordinary vocabulary." },
  146: { decision: 'pass', categories: [], rationale: "Friction between people is a common metaphor for interpersonal tension and clearly teaches the target." },
  147: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Dissociation is specialist mental-health vocabulary, and the clinical pairing makes depression carry unnecessary medical load." },
  148: { decision: 'pass', categories: [], rationale: "The question about moral dilemmas is a direct, understandable example of moral judgment." },
  149: { decision: 'reject', categories: ['archaic', 'context-too-hard'], rationale: "His Majesty, swift command, and resolute wording create an archaic historical scene that is not a modern default example for command." },
  150: { decision: 'reject', categories: ['context-too-hard', 'unnatural-English'], rationale: "Took the mickey is a region-specific idiom and makes dramatic depend on cultural knowledge unrelated to the target." },
  151: { decision: 'pass', categories: [], rationale: "Announcing a decision to remain in a group is a straightforward and natural use of remain." },
  152: { decision: 'pass', categories: [], rationale: "A male cardinal at a bird feeder gives cardinal a concrete animal meaning in a simple sentence." },
  153: { decision: 'pass', categories: [], rationale: "The cultural heritage sentence directly illustrates culture in a familiar national context without requiring background about the country." },
  154: { decision: 'pass', categories: [], rationale: "A brief escape from reality is a common expression that clearly shows brief as short in duration." },
  155: { decision: 'pass', categories: [], rationale: "The magnitude of a decision is an ordinary abstract collocation that makes magnitude clear as importance or scale." },
  156: { decision: 'pass', categories: [], rationale: "Asking whether the universe is bound by unseen rules gives bound a clear figurative limit meaning." },
  157: { decision: 'pass', categories: [], rationale: "Applying skepticism to different voices shows apply as using a method, with the contrast kept understandable." },
  158: { decision: 'pass', categories: [], rationale: "Opening palace doors to reveal a throne room is a complete, vivid narrative context that clearly demonstrates reveal." },
  159: { decision: 'pass', categories: [], rationale: "The contrast between an excellent idea and poor execution directly shows execution as how something is carried out." },
  160: { decision: 'pass', categories: [], rationale: "Asking what a boss would say about positive qualities makes positive a clear workplace adjective." },
  161: { decision: 'reject', categories: ['context-too-hard', 'unnatural-English'], rationale: "Elegance and grandeur make the spectacle sentence ornate and less natural for a default learner; grandeur is also harder than the target." },
  162: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Bad-faith lie and consideration frame worthy in adversarial argument language that adds unnecessary abstract and political load." },
  163: { decision: 'pass', categories: [], rationale: "A potato chip stuck between couch cushions gives chip a concrete everyday object context." },
  164: { decision: 'pass', categories: [], rationale: "An unlawful order is a clear ethical setting for comply, and the sentence directly contrasts following with refusing." },
  165: { decision: 'pass', categories: [], rationale: "A patient advocate for mental-health services gives advocate a concrete social role while keeping the sentence understandable." },
  166: { decision: 'reject', categories: ['archaic', 'weak-teaching-value'], rationale: "The silken-string and pearl-chain metaphor is ornate and aphoristic, so pearl is incidental to a difficult literary image." },
  167: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "Amphetamines and the insult techbros make insane part of a drug-related culture-war attack rather than a neutral teaching context." },
  168: { decision: 'pass', categories: [], rationale: "Squelching across a muddy field is a direct sensory scene that clearly illustrates muddy." },
  169: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Hominids and flint tools are specialist anthropology terms, so sophisticated is surrounded by vocabulary harder than the target." },
  170: { decision: 'pass', categories: [], rationale: "Saying someone is socially awkward in three languages is a concise modern and self-contained use of awkward." },
  171: { decision: 'pass', categories: [], rationale: "Second place in a hot-dog eating contest gives contest a familiar competition context." },
  172: { decision: 'pass', categories: [], rationale: "The garment industry is a common economic collocation, and the country reference does not prevent understanding garment." },
  173: { decision: 'pass', categories: [], rationale: "Jeopardizing an operation is a direct modern use of putting a plan at risk." },
  174: { decision: 'pass', categories: [], rationale: "Buying in bulk is a common shopping situation that makes bulk immediately clear." },
  175: { decision: 'pass', categories: [], rationale: "The changing evening sky being called a masterpiece gives the target a vivid but understandable figurative use." },
  176: { decision: 'pass', categories: [], rationale: "Medical issues being someone else's concern is a complete everyday boundary-setting sentence that shows concern." },
  177: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Hallucinogens, psychiatric conditions, and predisposition are specialist medical terms that make trigger unsuitable as a default context." },
  178: { decision: 'pass', categories: [], rationale: "Jazz chord progressions give chord a direct music meaning; the sentence is concise and the terms form a coherent teaching context." },
  179: { decision: 'pass', categories: [], rationale: "Removing outliers from analysis gives analysis a clear research meaning and remains readable for a general learner." },
  180: { decision: 'pass', categories: [], rationale: "The two contrasting uses of rejected make the interpersonal sense of reject explicit without needing prior context." },
  181: { decision: 'pass', categories: [], rationale: "A face telegraphing disgust is a natural figurative expression with a clear emotional target." },
  182: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Compression stockings make circulation depend on a specific medical treatment rather than an ordinary default context." },
  183: { decision: 'pass', categories: [], rationale: "Admitting to being reckless and overly trusting is a short, natural description of behavior." },
  184: { decision: 'pass', categories: [], rationale: "Extra virgin olive oil is a common food label that clearly demonstrates virgin as unprocessed or pure." },
  185: { decision: 'reject', categories: ['archaic', 'unnatural-English'], rationale: "The weary traveler and solace phrasing is literary and sentimental, so it does not feel like a modern default teaching sentence." },
  186: { decision: 'pass', categories: [], rationale: "Calling time a construct of the mind gives construct a clear abstract meaning in a self-contained question." },
  187: { decision: 'pass', categories: [], rationale: "Living in harmony with nature is a common, neutral expression that directly illustrates harmony." },
  188: { decision: 'pass', categories: [], rationale: "The familiar malice proverb gives attribute a clear meaning of assigning a cause or quality." },
  189: { decision: 'reject', categories: ['religious-heavy', 'fantastical-context'], rationale: "Reincarnation and a legendary hero make legend depend on fantastical religious background rather than a neutral example." },
  190: { decision: 'pass', categories: [], rationale: "The assumption about loving food is a simple conversational example that directly explains assumption." },
  191: { decision: 'pass', categories: [], rationale: "A conservation issue involving people and animals gives conservation a clear public-environmental meaning." },
  192: { decision: 'pass', categories: [], rationale: "Community outreach to reduce crime is a clear civic context that directly demonstrates crime." },
  193: { decision: 'reject', categories: ['death-heavy', 'proper-noun-heavy', 'context-dependent'], rationale: "An ill-fated liner leaving Australian waters hints at an unresolved disaster and adds a proper-name news context that is unnecessary for liner." },
  194: { decision: 'reject', categories: ['archaic', 'context-too-hard'], rationale: "Fall foul of and teacher's wrath are idiomatic and old-fashioned, so the sentence does not model foul in a clear modern way." },
  195: { decision: 'reject', categories: ['context-too-hard', 'specialist-background'], rationale: "A mortgage brokerage is specialist financial vocabulary and does not explain the target mortgage in an accessible everyday sentence." },
  196: { decision: 'reject', categories: ['weak-teaching-value', 'context-dependent'], rationale: "The slogan-like good up high, bad nearby gives no standalone explanation of ozone's meaning or relationship to the target." },
  197: { decision: 'pass', categories: [], rationale: "Space tourism becoming realistic gives concept a clear, contemporary abstract-use context." },
  198: { decision: 'pass', categories: [], rationale: "Energetic performances are a familiar arts context that directly shows energetic." },
  199: { decision: 'pass', categories: [], rationale: "The playful wish to be reincarnated as a dolphin is complete and gives dolphin a concrete animal reference." },
  200: { decision: 'pass', categories: [], rationale: "Christmas and Easter as national holidays gives Easter a clear cultural noun use; the sentence is simple and standalone." },
  201: { decision: 'reject', categories: ['archaic', 'unnatural-English'], rationale: "The inversion I dread more the peril and the literary word peril make this an unnatural modern example for dread." },
  202: { decision: 'reject', categories: ['context-dependent', 'context-too-hard'], rationale: "Furthermore signals missing preceding text, and external appearance, skeletal shape, and distinctiveness make the frog sentence academic and harder than the target." },
  203: { decision: 'pass', categories: [], rationale: "A relaxed mind showing in one's complexion is a concise, understandable appearance context." },
  204: { decision: 'pass', categories: [], rationale: "An archival interview and overrating success provide a coherent situation in which arrogant describes self-presentation." },
  205: { decision: 'pass', categories: [], rationale: "Mood disorder is a common, direct use of disorder, and the sentence explains the speaker's thoughts without technical detail." },
  206: { decision: 'pass', categories: [], rationale: "The future being predetermined or flexible creates a clear contrast that demonstrates flexible." },
  207: { decision: 'pass', categories: [], rationale: "The highest bidder determining who gets an item is a familiar auction context that makes item clear." },
  208: { decision: 'pass', categories: [], rationale: "Contrasting fission with fusion is a standard, concise science comparison that directly teaches fusion." },
  209: { decision: 'pass', categories: [], rationale: "Smashing cooked pumpkin pieces is a simple kitchen action that gives smash a clear verb use." },
  210: { decision: 'reject', categories: ['proper-noun-heavy', 'context-too-hard'], rationale: "Evanescence and a tribute band add an unnecessary proper name and music-specific background to tribute." },
  211: { decision: 'reject', categories: ['specialist-background', 'proper-noun-heavy', 'context-too-hard'], rationale: "Alpaca fleece, U.S. agriculture, and industry create specialist and acronym load that overwhelms segment." },
  212: { decision: 'pass', categories: [], rationale: "The short definition links criminal to committing a crime and makes the target immediately understandable." },
  213: { decision: 'pass', categories: [], rationale: "Employee-retention strategies are a common workplace context that directly shows retention." },
  214: { decision: 'pass', categories: [], rationale: "Biting one's lip in concentration is a familiar physical cue that clearly demonstrates concentration." },
  215: { decision: 'pass', categories: [], rationale: "Futurists predicting social effects gives predict a clear forward-looking meaning in a complete sentence." },
  216: { decision: 'pass', categories: [], rationale: "Background and foreground are explicitly contrasted around a family photograph-like scene, making background clear." },
  217: { decision: 'pass', categories: [], rationale: "An evolutionary advantage from regulating body temperature is a coherent science example with the target meaning obvious." },
  218: { decision: 'reject', categories: ['death-heavy', 'context-too-hard'], rationale: "Of this world and offspring create a literary death euphemism with harder family vocabulary, adding background unrelated to prosperous." },
  219: { decision: 'pass', categories: [], rationale: "Resenting an implication about engagement and money gives implication a clear interpersonal meaning." },
  220: { decision: 'pass', categories: [], rationale: "A filter that inverts light and dark colors makes invert concrete in a familiar interface instruction." },
  221: { decision: 'pass', categories: [], rationale: "The contrast between translation as artistry and comprehension gives comprehension a clear understanding-related meaning." },
  222: { decision: 'reject', categories: ['religious-heavy', 'archaic'], rationale: "The forgiveness proverb presents divine in a religious and literary frame that is not a neutral default context." },
  223: { decision: 'pass', categories: [], rationale: "The claim about natural hierarchy is a direct, readable example of hierarchy as an ordering system." },
  224: { decision: 'pass', categories: [], rationale: "The revocable-consent rule states the target precisely and remains a modern, self-contained social example." },
  225: { decision: 'pass', categories: [], rationale: "The periodic table example shows symmetry as structural balance, and the chemistry setting is concise and intelligible." },
  226: { decision: 'pass', categories: [], rationale: "Astronauts describing space as beautiful and overwhelming gives overwhelming a clear emotional scale." },
  227: { decision: 'reject', categories: ['religious-heavy', 'context-too-hard'], rationale: "Ethnic religions and tribal peoples are specialist, identity-sensitive categories that add unnecessary load to ethnic." },
  228: { decision: 'pass', categories: [], rationale: "Beach cleanup followed by accumulating trash gives accumulate a clear repeated-growth context." },
  229: { decision: 'pass', categories: [], rationale: "Predatory publishers looking credible illustrates credible through a familiar warning about deceptive appearance." },
  230: { decision: 'pass', categories: [], rationale: "Mercury's position among the planets gives the target a concrete scientific meaning with familiar language." },
  231: { decision: 'reject', categories: ['context-too-hard', 'specialist-background'], rationale: "Redundant infrastructure and service availability are IT operations jargon that is substantially harder than redundant." },
  232: { decision: 'pass', categories: [], rationale: "Bodily autonomy as a human right is a direct, modern definition-like use of autonomy with simple vocabulary." },
  233: { decision: 'reject', categories: ['context-too-hard', 'specialist-background'], rationale: "A judge nullifying a contract requires legal vocabulary and makes contract depend on the harder target-adjacent verb nullify." },
  234: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "Sue your pants off is an informal threat-like idiom, not a clear neutral example of sue's ordinary legal meaning." },
  235: { decision: 'reject', categories: ['political-heavy', 'proper-noun-heavy'], rationale: "Korean diplomacy places characterize in a named geopolitical context and adds specialist political vocabulary." },
  236: { decision: 'pass', categories: [], rationale: "A coupon redeemed in-store is a concrete retail situation that makes coupon clear." },
  237: { decision: 'reject', categories: ['context-too-hard', 'hate'], rationale: "Genetic clades and skin-color classification require specialist biology and sensitive racial background unrelated to basic genetic teaching." },
  238: { decision: 'pass', categories: [], rationale: "The anchor metaphor makes turbulent easy to understand as unstable or rough, and the sentence is complete." },
  239: { decision: 'pass', categories: [], rationale: "Foam in shoe soles is a concrete manufacturing example with simple vocabulary." },
  240: { decision: 'pass', categories: [], rationale: "Removing harmful bacteria from water gives bacteria a clear everyday health-and-cleaning context without graphic detail." },
  241: { decision: 'pass', categories: [], rationale: "I've got no clue is a common conversational phrase that directly illustrates clue." },
  242: { decision: 'pass', categories: [], rationale: "A king's throne made of wood is a straightforward historical object context that clearly shows throne." },
  243: { decision: 'pass', categories: [], rationale: "The contrast between a global language and a minority language directly teaches minority in a coherent language context." },
  244: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "Bust and bummer are both slangy, and the ellipsis leaves the intended meaning less clear than a modern default example should." },
  245: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Stripe rust, crops, and regional containment are specialist agriculture terms that overwhelm resistant." },
  246: { decision: 'pass', categories: [], rationale: "Sea levels pushing water inland gives inland a clear spatial direction in a current but understandable environmental context." },
  247: { decision: 'pass', categories: [], rationale: "Establishing trade routes is a clear historical-economic use of establish with simple syntax." },
  248: { decision: 'pass', categories: [], rationale: "Deleting comments that are no longer relevant is a concrete, modern example of relevant." },
  249: { decision: 'pass', categories: [], rationale: "Poking the bear is a common idiom that clearly conveys provoking a dangerous reaction." },
  250: { decision: 'reject', categories: ['context-too-hard', 'hate'], rationale: "Disparaging lies about disliked people introduces judgmental social conflict and a harder adjective, so it is not a neutral context for prone." },
  251: { decision: 'pass', categories: [], rationale: "Calm certainty is a concise emotional description that directly demonstrates certainty." },
  252: { decision: 'pass', categories: [], rationale: "Frequent-flyer miles are a familiar travel reward context that makes frequent clear." },
  253: { decision: 'pass', categories: [], rationale: "Moderation creating a hostile environment is an understandable online or workplace example with the target central." },
  254: { decision: 'pass', categories: [], rationale: "The question about global relations being stable is a simple abstract use that clearly shows stable." },
  255: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "A clan of fairies is fantastical and gives clan an unusual group context rather than a natural default example." },
  256: { decision: 'reject', categories: ['context-too-hard', 'specialist-background'], rationale: "Strings, integer types, and exceptions are programming terms that make exception inaccessible as a default learning context." },
  257: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "The sentence refers only to the incident without explaining what happened, so incident cannot be understood fully on its own." },
  258: { decision: 'pass', categories: [], rationale: "A Swiss Army knife is a familiar multi-use object that clearly demonstrates versatile." },
  259: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "The sarcastic claim about alternative medicine makes the target depend on a medical controversy rather than a neutral contrast." },
  260: { decision: 'pass', categories: [], rationale: "Manually inputting date and time on a device gives input a clear modern technical use without specialist detail." },
  261: { decision: 'pass', categories: [], rationale: "Polished furniture and gloss provide a concrete household context that makes furniture clear." },
  262: { decision: 'pass', categories: [], rationale: "Calling compassion humanity's greatest asset gives asset a clear figurative value meaning." },
  263: { decision: 'pass', categories: [], rationale: "Glasses used as a fashion accessory is a simple everyday example that directly teaches accessory." },
  264: { decision: 'pass', categories: [], rationale: "Infinite possibilities is a common abstract phrase that makes infinite clear." },
  265: { decision: 'pass', categories: [], rationale: "Cloth threads and pore size give pore a concrete physical meaning in a readable science example." },
  266: { decision: 'pass', categories: [], rationale: "The cost of premium membership is a common service-and-price context that makes premium clear." },
  267: { decision: 'reject', categories: ['context-too-hard', 'unnatural-English'], rationale: "A stock exchange chalking up numbers combines finance jargon with an idiom, making extraordinary less accessible than necessary." },
  268: { decision: 'reject', categories: ['unnatural-English', 'context-dependent'], rationale: "The repeated pronouns and wording about giving a delay to repay a debt are awkward and unclear modern English." },
  269: { decision: 'pass', categories: [], rationale: "Maintaining peace and order is a standard public-life collocation that clearly shows maintain." },
  270: { decision: 'pass', categories: [], rationale: "Sharing notes to compare interpretations is a natural study context that directly demonstrates compare." },
  271: { decision: 'pass', categories: [], rationale: "Common courtesy is a familiar social phrase that gives courtesy a clear meaning." },
  272: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Chromium exposure and valence state are specialist chemistry and health terms that overwhelm primarily." },
  273: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Declawing and cat-scratch disease create veterinary and medical load that is unnecessary for a default example of disease." },
  274: { decision: 'pass', categories: [], rationale: "Helping someone who is called a jerk is a simple interpersonal sentence that clearly shows jerk as an insult." },
  275: { decision: 'pass', categories: [], rationale: "Military recruiters visiting a school is a direct institutional context that makes military clear without graphic content." },
  276: { decision: 'pass', categories: [], rationale: "Waiting through hopelessness and gaining insight gives insight a clear reflective meaning in a complete sentence." },
  277: { decision: 'pass', categories: [], rationale: "Single and ready to mingle is a familiar playful phrase that directly illustrates mingle." },
  278: { decision: 'pass', categories: [], rationale: "The basis of an economic system is a clear abstract collocation that demonstrates basis without specialist detail." },
  279: { decision: 'reject', categories: ['syntax-too-complex', 'context-dependent'], rationale: "The long question nests motives, withholding information, and a comparison clause, so speculate is harder to process than necessary." },
  280: { decision: 'pass', categories: [], rationale: "Jiggling a handle to make a toilet flush is a concrete household action that clearly teaches flush." },
  281: { decision: 'pass', categories: [], rationale: "A world chess champion is a simple achievement context that makes champion obvious." },
  282: { decision: 'pass', categories: [], rationale: "The radioactive-waste superpowers line is a clearly marked humorous warning, and contact remains the central physical relation." },
  283: { decision: 'pass', categories: [], rationale: "Repeating mistakes is a familiar situation that gives destined a clear sense of being likely or fated." },
  284: { decision: 'reject', categories: ['context-too-hard', 'unnatural-English'], rationale: "Unaccountable and the inverted certainty phrasing are difficult and literary, so instantaneous is not presented in a natural default sentence." },
  285: { decision: 'reject', categories: ['medical-heavy', 'other'], rationale: "The personal statement about being an addict makes the example emotionally and medically loaded without enough teaching context for the target." },
  286: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Perspiration, heart-rate measurement, and sleep-quality monitoring create specialist health load that overwhelms participant." },
  287: { decision: 'pass', categories: [], rationale: "Blunt remarks following a moody temperament make blunt clear as direct or tactless." },
  288: { decision: 'pass', categories: [], rationale: "Leather heels clacking under a nurse's stride give leather a concrete material-and-clothing context." },
  289: { decision: 'pass', categories: [], rationale: "Once dust settles and truth becomes evident is a common phrase showing evident as clear or obvious." },
  290: { decision: 'pass', categories: [], rationale: "Finding abundance in a garden gives abundance a concrete, positive quantity context." },
  291: { decision: 'pass', categories: [], rationale: "Velvet fabric as a sign of luxury is a familiar material-and-status example that clearly teaches luxury." },
  292: { decision: 'reject', categories: ['violence', 'context-too-hard'], rationale: "A verbal altercation and whether it became physical add conflict and legal-like vocabulary unrelated to the basic target merely." },
  293: { decision: 'pass', categories: [], rationale: "Grief being difficult to handle is a direct emotional use that clearly teaches grief without graphic detail." },
  294: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Tail-fin contour and a first-of-its-kind fossil discovery are specialist paleontology details that overwhelm fossil." },
  295: { decision: 'reject', categories: ['political-heavy', 'context-dependent'], rationale: "The speaker's conservative identity and vague reference to what science proved make the sentence partisan and unclear on its own." },
  296: { decision: 'pass', categories: [], rationale: "Abuse of power is a common civic collocation that directly shows abuse as misuse rather than physical harm." },
  297: { decision: 'pass', categories: [], rationale: "Changes to a resume are a common job-search context that makes resume clear." },
  298: { decision: 'pass', categories: [], rationale: "Our own creation is a simple philosophical use that directly illustrates creation." },
  299: { decision: 'pass', categories: [], rationale: "A resort with everything needed for vacation gives resort a concrete travel context." },
}

const mandatoryDecisions: Record<string, ManualDecision> = {
  access: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "For access, instance variable and static method are programming terms that create specialist load substantially harder than the target." },
  famine: { decision: 'reject', categories: ['archaic', 'weak-teaching-value'], rationale: "The judges judged and famine in the land create a biblical-sounding literary setting rather than a modern ordinary learning context." },
  dodge: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Dodge the draft requires conscription and historical-policy background that is unnecessary for teaching the target's ordinary meaning." },
  permanent: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "The sentence is a sensitive medical-policy claim whose social background is unrelated to teaching permanent as a general adjective." },
  approach: { decision: 'reject', categories: ['medical-heavy', 'public-controversy', 'specialist-background'], rationale: "Evidence-based gender-affirming care places approach in a sensitive medical-policy debate and adds specialist background unrelated to the target." },
  burial: { decision: 'reject', categories: ['death-heavy', 'context-dependent'], rationale: "Shipped remains and family burial make this a death-heavy, context-dependent sentence that is not appropriate as a default example for burial." },
  deport: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Deporting people, borders, and authoritarianism make the target depend on a charged immigration-policy argument." },
  condemn: { decision: 'reject', categories: ['political-heavy', 'proper-noun-heavy', 'context-dependent'], rationale: "The comparison of Australia's and Canada's histories is a proper-name political dispute with background not needed to teach condemn." },
  irritate: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Mucous membranes and the medical eye-nose-throat context are specialist details that overwhelm a default example for irritate." },
  industrial: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Industrial applications of boron requires chemistry background and makes the surrounding vocabulary harder than the target." },
  detect: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Detecting nearby alternate realities is an unnatural fantasy premise that gives detect weak value for a default learning context." },
}

function rubricFor(decision: Decision, categories: string[]): Record<string, string> {
  const has = (names: string[]) => names.some((name) => categories.includes(name))
  return {
    defaultLearningAppropriateness: decision === 'pass' ? 'YES' : 'NO',
    targetTeachingValue: has(['weak-teaching-value', 'rare-sense']) ? 'FAIL' : 'PASS',
    contextVocabularyLoad: has(['context-too-hard', 'specialist-background', 'proper-noun-heavy']) ? 'FAIL' : 'PASS',
    syntaxSimplicity: has(['syntax-too-complex']) ? 'FAIL' : 'PASS',
    standaloneClarity: has(['context-dependent']) ? 'FAIL' : 'PASS',
    topicNeutrality: has(['political-heavy', 'medical-heavy', 'death-heavy', 'violence', 'extremism', 'hate', 'public-controversy', 'sexual', 'self-harm']) ? 'FAIL' : 'PASS',
    naturalModernEnglish: has(['unnatural-English', 'archaic', 'fantastical-context']) ? 'FAIL' : 'PASS',
    finalEditorDecision: decision === 'pass' ? 'PASS' : 'FAIL',
  }
}

function machineFlags(trace: Provenance): Record<string, number> {
  return Object.fromEntries(Object.entries(trace).filter(([, value]) => typeof value === 'number')) as Record<string, number>
}

function makeRow(candidate: Candidate, decision: ManualDecision, seed?: number, provenance?: Record<string, Provenance>) {
  const trace = provenance?.[candidate.word]
  if (!trace || trace.sentenceId !== candidate.sentenceId) throw new Error(`Provenance mismatch: ${candidate.word}|${candidate.sentenceId}`)
  return {
    ...candidate,
    ...(seed === undefined ? {} : { seed }),
    decision: decision.decision,
    categories: decision.categories,
    rationale: decision.rationale,
    reviewer: 'Lula-agent',
    reviewBasis: 'sentence-read-semantic-rubric',
    semanticDecisionSource: 'sentence-read',
    rubric: rubricFor(decision.decision, decision.categories),
    machineFlags: machineFlags(trace),
    severeInappropriate: false,
  }
}

function csvCell(value: unknown): string {
  const text = typeof value === 'string' ? value : JSON.stringify(value)
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
}

function toCsv(rows: Array<Record<string, unknown>>): string {
  const columns = ['word', 'sentenceId', 'sentence', 'decision', 'categories', 'rationale', 'reviewType', 'selectionSource', 'seed', 'semanticDecisionSource', 'defaultLearningAppropriateness', 'targetTeachingValue', 'contextVocabularyLoad', 'syntaxSimplicity', 'standaloneClarity', 'topicNeutrality', 'naturalModernEnglish', 'finalEditorDecision', 'severeInappropriate']
  const lines = rows.map((row) => columns.map((column) => column === 'categories' ? csvCell((row.categories as string[]).join('; ')) : column.startsWith('') && row.rubric ? csvCell(column === 'defaultLearningAppropriateness' ? (row.rubric as Record<string, string>).defaultLearningAppropriateness : column === 'targetTeachingValue' ? (row.rubric as Record<string, string>).targetTeachingValue : column === 'contextVocabularyLoad' ? (row.rubric as Record<string, string>).contextVocabularyLoad : column === 'syntaxSimplicity' ? (row.rubric as Record<string, string>).syntaxSimplicity : column === 'standaloneClarity' ? (row.rubric as Record<string, string>).standaloneClarity : column === 'topicNeutrality' ? (row.rubric as Record<string, string>).topicNeutrality : column === 'naturalModernEnglish' ? (row.rubric as Record<string, string>).naturalModernEnglish : column === 'finalEditorDecision' ? (row.rubric as Record<string, string>).finalEditorDecision : row[column]) : csvCell(row[column])).join(','))
  return `${columns.join(',')}\n${lines.join('\n')}\n`
}

const phaseADocument = JSON.parse(await readFile(phaseAPath, 'utf8')) as { seed: number; rows: Candidate[] }
const mandatoryDocument = JSON.parse(await readFile(mandatoryPath, 'utf8')) as { rows: Candidate[] }
const provenance = JSON.parse(await readFile(provenancePath, 'utf8')) as Record<string, Provenance>
if (Object.keys(phaseADecisions).length !== phaseADocument.rows.length) throw new Error(`Phase A decision count mismatch: ${Object.keys(phaseADecisions).length} vs ${phaseADocument.rows.length}`)
for (let index = 0; index < phaseADocument.rows.length; index += 1) if (!phaseADecisions[index]) throw new Error(`Missing Phase A decision at index ${index}`)
for (const word of Object.keys(mandatoryDecisions)) if (!mandatoryDocument.rows.some((row) => row.word === word)) throw new Error(`Missing mandatory candidate: ${word}`)

const phaseARows = phaseADocument.rows.map((candidate, index) => makeRow(candidate, phaseADecisions[index], phaseADocument.seed, provenance))
const mandatoryRows = mandatoryDocument.rows.map((candidate) => makeRow(candidate, mandatoryDecisions[candidate.word], undefined, provenance))
const allRationales = [...phaseARows, ...mandatoryRows].map((row) => row.rationale)
const rationaleFrequency = new Map<string, number>()
for (const rationale of allRationales) rationaleFrequency.set(rationale, (rationaleFrequency.get(rationale) ?? 0) + 1)
const exactDuplicateRationaleCount = [...rationaleFrequency.values()].filter((count) => count > 1).reduce((total, count) => total + count - 1, 0)
const genericRationaleCount = allRationales.filter((rationale) => rationale.length < 60 || /^Read in full:/i.test(rationale) || /^This is complete and natural/i.test(rationale)).length
const shortRationaleCount = allRationales.filter((rationale) => rationale.length < 45).length
const rationaleQuality = {
  reviewedRows: allRationales.length,
  exactDuplicateRationaleCount,
  genericRationaleCount,
  genericRationaleShare: Number((genericRationaleCount / allRationales.length).toFixed(4)),
  shortRationaleCount,
  gate: exactDuplicateRationaleCount <= 5 && genericRationaleCount / allRationales.length < 0.05,
  method: 'Audit-only reviewer-quality QA; it never creates or changes semantic decisions.',
}

await mkdir(auditRoot, { recursive: true })
await writeFile(resolve(auditRoot, 'phase-a-random-review.json'), `${JSON.stringify({
  round: 'Context Final Semantic Acceptance - Round 5',
  seed: phaseADocument.seed,
  sampleSize: phaseARows.length,
  semanticDecisionSource: 'sentence-read',
  machineMetricsRole: 'triage metadata only; never used to assign decision',
  rows: phaseARows,
}, null, 2)}\n`, 'utf8')
await writeFile(resolve(auditRoot, 'phase-a-random-review.csv'), toCsv(phaseARows))
await writeFile(resolve(auditRoot, 'mandatory-recheck.json'), `${JSON.stringify({
  round: 'Context Final Semantic Acceptance - Round 5',
  sampleSize: mandatoryRows.length,
  semanticDecisionSource: 'sentence-read',
  rows: mandatoryRows,
}, null, 2)}\n`, 'utf8')
await writeFile(resolve(auditRoot, 'mandatory-recheck.md'), `# Round 5 mandatory recheck\n\nAll 11 known-problem items were read again. Each is rejected for the sentence-specific reason below and is added to durable curation before rebuild.\n\n| Word | Sentence ID | Decision | Categories | Rationale |\n| --- | ---: | --- | --- | --- |\n${mandatoryRows.map((row) => `| ${row.word} | ${row.sentenceId} | ${row.decision.toUpperCase()} | ${row.categories.join(' / ')} | ${row.rationale} |`).join('\n')}\n`, 'utf8')
await writeFile(resolve(auditRoot, 'rationale-quality-report.json'), `${JSON.stringify(rationaleQuality, null, 2)}\n`, 'utf8')

console.log(`Round 5 sentence-read review written: phaseA=${phaseARows.length}, phaseAFails=${phaseARows.filter((row) => row.decision === 'reject').length}, mandatory=${mandatoryRows.length}, mandatoryFails=${mandatoryRows.filter((row) => row.decision === 'reject').length}, rationaleDuplicates=${exactDuplicateRationaleCount}, genericShare=${(rationaleQuality.genericRationaleShare * 100).toFixed(1)}%`)
