import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

type Decision = 'pass' | 'reject'
interface ManualDecision { decision: Decision; categories: string[]; rationale: string }
interface Candidate { word: string; sentenceId: number; sentence: string; reviewType: string; semanticDecisionSource: string }
interface Provenance { sentenceId: number; source: string; qualityScore: number; [key: string]: number | string }

const root = resolve(import.meta.dirname, '..')
const auditRoot = resolve(root, 'audit/v1.3-context-final-semantic')
const candidatePath = resolve(auditRoot, 'phase-a-post-curation-candidates.json')
const provenancePath = resolve(root, 'data-source/examples/example-provenance.json')

const decisions: Record<number, ManualDecision> = {
  0: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "Tinfoil hats and a tinfoil beret require niche conspiracy imagery, so variation is not shown in a normal default context." },
  1: { decision: 'pass', categories: [], rationale: "Maintaining order during an emergency drill gives drill a clear, ordinary practice-event meaning." },
  2: { decision: 'pass', categories: [], rationale: "The direct question asks the learner to identify irony in a familiar situation and keeps the target central." },
  3: { decision: 'pass', categories: [], rationale: "Actions that look generous but have a profit motive clearly illustrate the target contrast." },
  4: { decision: 'pass', categories: [], rationale: "A tree stump at the bottom of a lake is a concrete, self-contained noun context." },
  5: { decision: 'pass', categories: [], rationale: "Traveling beyond the solar system gives beyond a clear spatial-extension meaning." },
  6: { decision: 'pass', categories: [], rationale: "Peace being maintained across a region gives region a simple geographic meaning." },
  7: { decision: 'pass', categories: [], rationale: "The question about complaining about dental treatment is an ordinary service problem that clearly shows complain." },
  8: { decision: 'pass', categories: [], rationale: "Spice things up is a common figurative expression built on the familiar food meaning of spice." },
  9: { decision: 'pass', categories: [], rationale: "The country example connects poverty to concrete progress in health and education without needing political background." },
  10: { decision: 'pass', categories: [], rationale: "Autonomous ships provide a current but intelligible example of autonomous systems operating independently." },
  11: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Genitive case and Russian grammar are specialist linguistic terms that overwhelm the basic target denote." },
  12: { decision: 'pass', categories: [], rationale: "A sales pitch not going well is a familiar workplace situation that directly illustrates pitch." },
  13: { decision: 'pass', categories: [], rationale: "A game ending in defeat is a short, direct result context for defeat." },
  14: { decision: 'pass', categories: [], rationale: "Sport as a factor in social integration gives factor a clear cause or contributing-element meaning." },
  15: { decision: 'reject', categories: ['death-heavy', 'context-too-hard'], rationale: "Mass beaching of whales and dolphins is an unusual animal-death phenomenon that adds distress and specialist context unrelated to mass." },
  16: { decision: 'reject', categories: ['specialist-background', 'context-dependent'], rationale: "Construction, sentences, and a missing antecedent require grammar analysis that is much harder than alter." },
  17: { decision: 'pass', categories: [], rationale: "An enormous beetle among familiar plants gives enormous a concrete size meaning." },
  18: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Affirming the consequent and formal logical fallacy are technical logic terms that make formal inaccessible as a default example." },
  19: { decision: 'pass', categories: [], rationale: "Exploring ancient ruins is a common travel context that directly demonstrates ancient." },
  20: { decision: 'pass', categories: [], rationale: "An attitude of challenge and defiance gives attitude a clear way-of-facing-something meaning." },
  21: { decision: 'reject', categories: ['death-heavy', 'context-dependent'], rationale: "A prisoner dying before release adds an unnecessary death narrative and leaves the emotional situation unsuitable for default learning." },
  22: { decision: 'pass', categories: [], rationale: "Evaporation creating a temperature drop is a clear, readable science process that directly shows process." },
  23: { decision: 'pass', categories: [], rationale: "Lion dances as one facet of a culture gives facet a clear part-of-a-whole meaning." },
  24: { decision: 'reject', categories: ['medical-heavy', 'self-harm'], rationale: "Injecting bleach into an arm is dangerous self-harm imagery and an unacceptable default medical context for inject." },
  25: { decision: 'pass', categories: [], rationale: "A band playing covers and original songs gives original a familiar music contrast." },
  26: { decision: 'pass', categories: [], rationale: "Choking on stomach acid is unpleasant but simple, direct, and clearly demonstrates acid as a substance." },
  27: { decision: 'pass', categories: [], rationale: "A cat chasing a cursor gives chase a concrete, harmless everyday action." },
  28: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "Calling Bitcoin a disaster for humanity makes disaster part of a polarized financial and technological claim rather than a neutral example." },
  29: { decision: 'pass', categories: [], rationale: "A morning jog interrupted by dog poop is a clear, ordinary activity context for jog." },
  30: { decision: 'pass', categories: [], rationale: "A person's approach to learning is a natural, relevant use that clearly shows approach as a method." },
  31: { decision: 'pass', categories: [], rationale: "Fertilizer runoff and sewage management provide a coherent environmental context in which fertilizer is central." },
  32: { decision: 'pass', categories: [], rationale: "The cheetah and domestic cat comparison gives domestic a familiar household-animal contrast." },
  33: { decision: 'reject', categories: ['other', 'weak-teaching-value'], rationale: "Butt rock is niche slang and the sentence gives album little teaching value beyond a vague music label." },
  34: { decision: 'pass', categories: [], rationale: "Relying on ferries in a river-filled country gives rely a clear transportation dependence meaning." },
  35: { decision: 'pass', categories: [], rationale: "An extensive investigation clearing someone of wrongdoing is a complete and familiar institutional context." },
  36: { decision: 'pass', categories: [], rationale: "Breaking a cycle of existence gives cycle a clear repeated-pattern meaning in an understandable abstract question." },
  37: { decision: 'pass', categories: [], rationale: "Crisis-management skills at work give management a direct, modern workplace use." },
  38: { decision: 'pass', categories: [], rationale: "A new planet in a galaxy is a simple astronomy context that makes galaxy concrete." },
  39: { decision: 'reject', categories: ['context-too-hard', 'specialist-background'], rationale: "A stock brokerage sign assumes specialized finance vocabulary and gives stock an ambiguous context for a default learner." },
  40: { decision: 'pass', categories: [], rationale: "Knowledge pursued for its own sake is a common phrase that clearly demonstrates sake." },
  41: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "The cancer-cell ideology metaphor adds medical and ideological framing that is unnecessary for the target sake." },
  42: { decision: 'pass', categories: [], rationale: "Extending legs to a certain extent gives extent a direct measure-of-range meaning." },
  43: { decision: 'pass', categories: [], rationale: "An elite preparatory school is a straightforward education context that makes elite clear." },
  44: { decision: 'pass', categories: [], rationale: "Passing a sponge is a short, ordinary household request with the target unambiguous." },
  45: { decision: 'pass', categories: [], rationale: "The radius of a hydrogen atom gives radius a precise but accessible scientific meaning." },
  46: { decision: 'pass', categories: [], rationale: "A challenging attitude accompanied by defiance makes defiance clear in a complete narrative description." },
  47: { decision: 'pass', categories: [], rationale: "Bad texture compared with acceptable taste gives texture a concrete sensory meaning." },
  48: { decision: 'reject', categories: ['violence', 'context-too-hard'], rationale: "A verbal altercation and whether it became physical add conflict and harder vocabulary unrelated to teaching verbal." },
  49: { decision: 'pass', categories: [], rationale: "A cheese wedge is a concrete food shape that gives wedge an immediate physical meaning." },
  50: { decision: 'reject', categories: ['political-heavy', 'other'], rationale: "Unmoderated hellholes and avoid like the plague use hostile internet slang and a loaded comparison instead of a neutral context for avoid." },
  51: { decision: 'pass', categories: [], rationale: "Showing a sensitive side is a natural interpersonal use that directly illustrates sensitive." },
  52: { decision: 'reject', categories: ['violence'], rationale: "Keeping a finger on a trigger makes trigger depend on a weapon context that adds unnecessary violence to default learning." },
  53: { decision: 'pass', categories: [], rationale: "Appealing to people's reasonable side gives appeal a clear interpersonal persuasion meaning." },
  54: { decision: 'pass', categories: [], rationale: "Moving forward with caution is a common decision-making phrase that clearly shows caution." },
  55: { decision: 'pass', categories: [], rationale: "The playful contrast between friendly-looking writing and evil speech gives evil a clear figurative use." },
  56: { decision: 'pass', categories: [], rationale: "Friends not abandoning each other is a simple relationship context that directly shows abandon." },
  57: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "Inordinate explanation and complaining make the apology sentence depend on an uncommon adjective and a vague complaint context." },
  58: { decision: 'pass', categories: [], rationale: "An associate degree is a common educational credential that gives associate a clear noun meaning." },
  59: { decision: 'pass', categories: [], rationale: "Initial cost contrasted with upkeep gives initial a direct time-order meaning." },
  60: { decision: 'pass', categories: [], rationale: "Protecting the environment for future generations is a familiar, neutral civic context." },
  61: { decision: 'pass', categories: [], rationale: "A cheating scandal affecting a university reputation gives scandal a clear public-misconduct meaning." },
  62: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "The speaker refers to controversial sentences and personal taste without a clear situation, so controversial is not taught standalone." },
  63: { decision: 'reject', categories: ['context-too-hard', 'public-controversy'], rationale: "A fake numbers station is a niche espionage and trolling context that adds specialist background to fake." },
  64: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Chemical preservatives, borax, boric acid, and sulfite create specialist chemistry load that overwhelms principal." },
  65: { decision: 'pass', categories: [], rationale: "A royal banquet described as a feast gives banquet a concrete, familiar event context." },
  66: { decision: 'pass', categories: [], rationale: "The oak standing unshaken in a storm gives oak a clear tree reference with a simple metaphor." },
  67: { decision: 'pass', categories: [], rationale: "The cycle-of-existence question gives existence a clear abstract meaning without needing a prior story." },
  68: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "No strand goes with the other is still awkward and does not provide a clear natural use of strand." },
  69: { decision: 'pass', categories: [], rationale: "The contrast between infinite and finite gives finite a precise, self-contained meaning." },
  70: { decision: 'pass', categories: [], rationale: "Decent information about what to do is a common everyday request that clearly shows decent." },
  71: { decision: 'reject', categories: ['political-heavy', 'public-controversy', 'context-too-hard'], rationale: "Kiwifarms, reactionaries, and cancel culture create a niche political controversy that overwhelms claim." },
  72: { decision: 'pass', categories: [], rationale: "Slashing energy consumption is a clear modern use of slash as sharply reducing something." },
  73: { decision: 'pass', categories: [], rationale: "Skipping a show's theme song is a familiar media habit that directly demonstrates skip." },
  74: { decision: 'pass', categories: [], rationale: "Forging ahead to accomplish a dream gives accomplish a clear goal-completion meaning." },
  75: { decision: 'pass', categories: [], rationale: "A contribution waiting for approval is a concise workplace or group context that makes contribution clear." },
  76: { decision: 'pass', categories: [], rationale: "Privacy protecting who we are gives essence a clear central-quality meaning in a modern context." },
  77: { decision: 'pass', categories: [], rationale: "Divide-and-conquer strategies involving groups gives involve a clear relation between an action and people." },
  78: { decision: 'pass', categories: [], rationale: "A cat's wild ancestor gives ancestor a concrete family-line meaning with familiar vocabulary." },
  79: { decision: 'pass', categories: [], rationale: "Uranus being dim to the naked eye provides a clear light-level meaning for dim." },
  80: { decision: 'pass', categories: [], rationale: "A cat being cute while asleep and awake is a simple, natural description of cute." },
  81: { decision: 'pass', categories: [], rationale: "Having a monopoly on the truth is a clear figurative use of monopoly as exclusive control." },
  82: { decision: 'pass', categories: [], rationale: "Truth emerging at dawn gives emerge a direct coming-to-light meaning." },
  83: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "The fetus viability statement is a sensitive medical-policy context that adds unnecessary controversy to merely." },
  84: { decision: 'pass', categories: [], rationale: "Conserving water in a garden is a practical environmental example that clearly shows conserve." },
  85: { decision: 'pass', categories: [], rationale: "Choosing whether to stop an interaction gives interaction a clear, modern social meaning." },
  86: { decision: 'reject', categories: ['weak-teaching-value', 'context-too-hard'], rationale: "Jumped the shark is a media idiom and does not teach the literal target shark in a useful default context." },
  87: { decision: 'pass', categories: [], rationale: "The question whether every action has a consequence is a direct and readable abstract example." },
  88: { decision: 'pass', categories: [], rationale: "An orientation course is a familiar educational setting that makes orientation clear." },
  89: { decision: 'pass', categories: [], rationale: "Industrial parks and investors provide a coherent modern economic context for industrial." },
  90: { decision: 'pass', categories: [], rationale: "Space tourism becoming more realistic gives realistic a clear contrast with fantasy." },
  91: { decision: 'pass', categories: [], rationale: "The sentence uses oppose in a readable logical contrast about support and censorship." },
  92: { decision: 'pass', categories: [], rationale: "A burger costing a buck is a familiar informal price context that clearly shows buck." },
  93: { decision: 'reject', categories: ['archaic', 'unnatural-English'], rationale: "The night cradles the weary soul is poetic and sentimental rather than modern ordinary English for weary." },
  94: { decision: 'pass', categories: [], rationale: "Remaining loyal in difficult times is a common relationship question that directly shows loyal." },
  95: { decision: 'pass', categories: [], rationale: "A crowd responding to a royal wave gives crowd a concrete public-group meaning." },
  96: { decision: 'pass', categories: [], rationale: "Reaching a summit at dawn is a simple physical journey context that makes summit clear." },
  97: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Freestyle aerial skiing is a specialized sport context that makes aerial harder than necessary for a default learner." },
  98: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Quantitative verse in Latin poetry is specialist literary material and does not provide a simple default context for verse." },
  99: { decision: 'pass', categories: [], rationale: "Being driven by passion is a short, modern question that directly illustrates passion." },
  100: { decision: 'pass', categories: [], rationale: "Let's assume you're right is a familiar conversational conditional that clearly demonstrates assume." },
  101: { decision: 'pass', categories: [], rationale: "Tactile sensation from reading a physical book gives sensation a concrete sensory meaning." },
  102: { decision: 'pass', categories: [], rationale: "Going through a messy divorce is an ordinary relationship context that clearly illustrates divorce." },
  103: { decision: 'pass', categories: [], rationale: "Put some elbow grease into it is a common idiom built around grease as effort." },
  104: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Spinal curvature and lumbar support are anatomical and medical terms that make conform harder than the target." },
  105: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Refusing to acknowledge an agenda frames acknowledge in an accusatory political argument rather than a neutral context." },
  106: { decision: 'pass', categories: [], rationale: "An old cathedral attracting tourists gives cathedral a clear public-building meaning." },
  107: { decision: 'pass', categories: [], rationale: "Overhearing a word that the speaker understands is a complete and natural listening context for overhear." },
  108: { decision: 'pass', categories: [], rationale: "Security cameras installed on property to deter thieves gives property a clear ownership-and-place meaning." },
  109: { decision: 'reject', categories: ['death-heavy', 'archaic'], rationale: "The remainder of his days in quiet reflection is a death-adjacent literary phrase that is not a modern default context." },
  110: { decision: 'pass', categories: [], rationale: "A space journey testing endurance is a clear challenge context with familiar vocabulary." },
  111: { decision: 'reject', categories: ['context-too-hard', 'other'], rationale: "Crash at your pad is informal slang, and pad makes the target crash depend on cultural knowledge outside the basic verb meaning." },
  112: { decision: 'reject', categories: ['context-too-hard', 'weak-teaching-value'], rationale: "Conjure, secluded, and utopian create unusually difficult descriptive vocabulary around the simple target glance." },
  113: { decision: 'pass', categories: [], rationale: "A reference work powered by discussion gives reference a clear information-source meaning despite the light metaphor." },
  114: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "Capitalism and unearned power make insane part of an ideological economic attack rather than a neutral context." },
  115: { decision: 'pass', categories: [], rationale: "Photographic identification and a passport give identification a concrete travel-document meaning." },
  116: { decision: 'pass', categories: [], rationale: "A stream of consciousness compared with a hurricane provides a vivid but understandable figurative use." },
  117: { decision: 'reject', categories: ['context-too-hard'], rationale: "Quantifying prosperity and comparing countries creates academic economic vocabulary that is harder than inherent." },
  118: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Affirming the consequent and formal logical fallacy are technical logic terms that overwhelm consequent." },
  119: { decision: 'pass', categories: [], rationale: "Coastal erosion submerging a fishing community gives erosion a clear environmental process meaning." },
  120: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Deep vein thrombosis and pregnancy make vein depend on specialist medical background rather than a default context." },
  121: { decision: 'pass', categories: [], rationale: "Disease spreading through a town is a direct, understandable example of disease." },
  122: { decision: 'pass', categories: [], rationale: "Minimum wage gives minimum a familiar lower-limit meaning in a workplace context." },
  123: { decision: 'pass', categories: [], rationale: "Open communication supporting mutual learning gives mutual a clear shared relationship meaning." },
  124: { decision: 'reject', categories: ['public-controversy', 'context-too-hard'], rationale: "A search engine making things up turns revolutionary into a current technology controversy and adds unnecessary background." },
  125: { decision: 'pass', categories: [], rationale: "Sparkle in someone's eyes is a common, concrete visual expression that clearly teaches sparkle." },
  126: { decision: 'pass', categories: [], rationale: "History repeating on a larger scale gives scale a clear comparative size meaning." },
  127: { decision: 'pass', categories: [], rationale: "A scientific breakthrough linked to a person's responsibility gives breakthrough a familiar achievement meaning." },
  128: { decision: 'pass', categories: [], rationale: "Everyone being entitled to be an idiot is a simple, direct use of idiot as an insult." },
  129: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "The mission's most vulnerable is incomplete without knowing who or what is vulnerable, so the target is not standalone." },
  130: { decision: 'reject', categories: ['rare-sense', 'proper-noun-heavy', 'weak-teaching-value'], rationale: "Polish refers to nationality in a flag correction rather than the common target sense, and the proper-name contrast adds little teaching value." },
  131: { decision: 'pass', categories: [], rationale: "A whole brood accompanying someone gives brood a clear family-group meaning." },
  132: { decision: 'reject', categories: ['context-too-hard'], rationale: "Quantifying prosperity and comparing countries create academic economic vocabulary that is harder than prosperous." },
  133: { decision: 'reject', categories: ['hate', 'public-controversy'], rationale: "Following a Black customer because of race is an identity-based discriminatory context that is inappropriate for default learning of clerk." },
  134: { decision: 'reject', categories: ['archaic', 'context-too-hard'], rationale: "Rare merit, fastidious critic, and the inverted sentence structure create literary load that overwhelms merit." },
  135: { decision: 'pass', categories: [], rationale: "Scraping by on current income is a familiar financial situation that clearly illustrates scrape." },
  136: { decision: 'pass', categories: [], rationale: "Comparing two languages gives contrast a direct comparison meaning in a concise sentence." },
  137: { decision: 'reject', categories: ['context-too-hard', 'rare-sense'], rationale: "Romance and Germanic language classifications are specialist linguistic senses that make romance less accessible as a default example." },
  138: { decision: 'reject', categories: ['archaic', 'fantastical-context'], rationale: "Enchanting and defying a ruler's power create an archaic fantasy scene that is not a modern default context for defy." },
  139: { decision: 'pass', categories: [], rationale: "Self-care being essential for health is a common modern wellness context that clearly shows essential." },
  140: { decision: 'pass', categories: [], rationale: "A police warrant is a familiar legal object context that directly illustrates warrant." },
  141: { decision: 'reject', categories: ['medical-heavy', 'political-heavy'], rationale: "Diseases afflicting marginalized communities adds medical and social-policy load that is unnecessary for afflict." },
  142: { decision: 'reject', categories: ['political-heavy', 'violence', 'context-too-hard'], rationale: "Smuggling contraband across a border combines crime and immigration-policy background that overwhelms tunnel." },
  143: { decision: 'pass', categories: [], rationale: "Sculpting abstract figures from clay gives abstract a clear art-related meaning with concrete action." },
  144: { decision: 'pass', categories: [], rationale: "Folding along lines to make a crease is a direct household instruction that clearly shows fold." },
  145: { decision: 'pass', categories: [], rationale: "Listening to classical music is a familiar cultural preference that makes classical clear." },
  146: { decision: 'pass', categories: [], rationale: "The medium is not the message is a concise, recognizable statement that demonstrates medium as a channel." },
  147: { decision: 'reject', categories: ['other', 'context-too-hard'], rationale: "Hellholes and avoid like the plague use hostile internet slang and an intense comparison that is not a neutral context for plague." },
  148: { decision: 'pass', categories: [], rationale: "A terraced house contrasted with a mansion gives mansion a clear ordinary property meaning." },
  149: { decision: 'pass', categories: [], rationale: "Trademark protection ending at national borders gives trademark a clear legal-business meaning." },
  150: { decision: 'pass', categories: [], rationale: "A repeated historical event is a complete and natural example of phenomenon." },
  151: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "The laughing sieve and smiling sheepskin rug are an unnatural fable-like image that does not teach coarse clearly." },
  152: { decision: 'pass', categories: [], rationale: "Coffee roasters combining beans gives combine a concrete production meaning with simple vocabulary." },
  153: { decision: 'pass', categories: [], rationale: "A plaster cast and air travel provide a clear everyday medical-travel context for plaster." },
  154: { decision: 'pass', categories: [], rationale: "A band's indefinite hiatus is a common entertainment context that directly illustrates indefinite." },
  155: { decision: 'pass', categories: [], rationale: "Sustainable farming helping a garden thrive gives thrive a clear healthy-growth meaning." },
  156: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Feed pellets for farmed fish create specialized agriculture vocabulary that makes alternative harder than necessary." },
  157: { decision: 'pass', categories: [], rationale: "A single encounter at a party is a clear, ordinary example of meeting someone once." },
  158: { decision: 'pass', categories: [], rationale: "Plants attracting pollinators gives attract a concrete biological relationship that is easy to follow." },
  159: { decision: 'pass', categories: [], rationale: "Remembering genetics and vocabulary learned at school gives memorize a direct study context." },
  160: { decision: 'pass', categories: [], rationale: "Finding one's Danish pronunciation ridiculous is a simple self-evaluation context that clearly shows ridiculous." },
  161: { decision: 'pass', categories: [], rationale: "Improvement as a commitment to oneself gives commitment a clear personal-goal meaning." },
  162: { decision: 'pass', categories: [], rationale: "Mountains as eternal guardians is a vivid but understandable figurative use of eternal." },
  163: { decision: 'pass', categories: [], rationale: "An extended submission deadline is a direct administrative example that clearly shows deadline." },
  164: { decision: 'pass', categories: [], rationale: "Acquiring a language through exposure gives acquire a clear learning meaning in a concise statement." },
  165: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Smuggling contraband across a border adds criminal and border-policy background unrelated to teaching border." },
  166: { decision: 'pass', categories: [], rationale: "Young animals hatching and entering protected pens gives hatch a clear biological process meaning." },
  167: { decision: 'reject', categories: ['archaic', 'weak-teaching-value'], rationale: "My lady and a stroll in gardens give stroll an old-fashioned literary setting rather than a normal modern default context." },
  168: { decision: 'pass', categories: [], rationale: "A Halloween costume is a familiar seasonal object context that clearly demonstrates costume." },
  169: { decision: 'reject', categories: ['public-controversy', 'sexual'], rationale: "Drag queen story hour is a current identity and culture-war context that adds controversy unrelated to teaching drag." },
  170: { decision: 'pass', categories: [], rationale: "A car skidding on a slippery road is a clear physical situation that directly shows slippery." },
  171: { decision: 'pass', categories: [], rationale: "Asking whether something was the only option is a concise, natural use of option." },
  172: { decision: 'pass', categories: [], rationale: "One person wearing a cape gives cape a concrete clothing meaning without background." },
  173: { decision: 'pass', categories: [], rationale: "The hypocrisy comparison gives condemn a clear judgment meaning in a complete sentence." },
  174: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "Corporate media is a partisan media framing that adds current political controversy to the target corporate." },
  175: { decision: 'pass', categories: [], rationale: "Heterogeneous and homogeneous are explicitly contrasted, making homogeneous clear as alike in composition." },
  176: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Directional microphones built into eyeglass frames create technical hardware detail that overwhelms array." },
  177: { decision: 'pass', categories: [], rationale: "Constant lies make constant clear as repeated or continuing over time." },
  178: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Alternate realities are a fantasy premise that makes alternate unclear as a useful ordinary contrast." },
  179: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "The opioid epidemic and lack of consequences create a charged medical-policy context unrelated to responsible." },
  180: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "An Esperanto congress adds a niche language-community background and proper-name-like load to congress." },
  181: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Decolonization talks place protest in a specialized political-history context that is unnecessary for the target." },
  182: { decision: 'reject', categories: ['context-too-hard'], rationale: "Scalability and market-demand language create business jargon that makes demand harder than a default context should." },
  183: { decision: 'reject', categories: ['unnatural-English', 'weak-teaching-value'], rationale: "A bridge becoming an ambient music generator is an implausible software joke that gives upgrade weak default teaching value." },
  184: { decision: 'pass', categories: [], rationale: "Rolling back an update is a common modern software action that clearly shows update." },
  185: { decision: 'pass', categories: [], rationale: "Asking about bathing after surgery is a direct and understandable health context for surgery." },
  186: { decision: 'pass', categories: [], rationale: "A yellow light and a car entering a junction give intersection a concrete traffic meaning." },
  187: { decision: 'reject', categories: ['sexual', 'weak-teaching-value'], rationale: "Screw me up is an ambiguous informal phrase with a sexual reading, so it is not a clear default example." },
  188: { decision: 'pass', categories: [], rationale: "A global recession and economic recovery give recession a familiar, direct meaning." },
  189: { decision: 'pass', categories: [], rationale: "Thieves making off with a haul gives haul a clear quantity-of-stolen-goods meaning." },
  190: { decision: 'pass', categories: [], rationale: "Checking an order's status is an ordinary customer-service context that directly illustrates status." },
  191: { decision: 'pass', categories: [], rationale: "Encouraging people to protect the environment gives encourage a clear social-action use." },
  192: { decision: 'reject', categories: ['context-too-hard', 'public-controversy'], rationale: "Fiat currency, Bitcoin, and fixed physical resources make definition depend on specialist financial debate." },
  193: { decision: 'pass', categories: [], rationale: "A pedal generator converting human effort into electricity gives convert a concrete transformation meaning." },
  194: { decision: 'pass', categories: [], rationale: "Calling a watermelon exceptional is a simple, natural evaluation of quality." },
  195: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "The cosmic web is an astronomy concept that requires specialist background and does not teach web as an ordinary object." },
  196: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Aqueous, solvent, and solution form a chemistry definition whose surrounding vocabulary is harder than the target." },
  197: { decision: 'pass', categories: [], rationale: "Good triumphing over evil is a widely understandable moral contrast that clearly shows triumph." },
  198: { decision: 'pass', categories: [], rationale: "Objecting to a friend calling in another friend is a complete social example of objection." },
  199: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Cornucopians and the cornucopia of Greek legend require economic and mythological background that overwhelms legend." },
  200: { decision: 'pass', categories: [], rationale: "Clear, concise writing that avoids jargon is a direct educational context for concise." },
  201: { decision: 'reject', categories: ['medical-heavy', 'weak-teaching-value'], rationale: "A bonus goiter introduces an unexplained medical abnormality that is unrelated to teaching bonus." },
  202: { decision: 'reject', categories: ['public-controversy', 'context-too-hard'], rationale: "Kiwifarms and cancel culture create a niche political controversy that is not a neutral context for cancel." },
  203: { decision: 'pass', categories: [], rationale: "Not foreseeing a future trip to Boston is a clear, ordinary use of foresee." },
  204: { decision: 'pass', categories: [], rationale: "Graphic design for T-shirt sites is a familiar job activity that clearly illustrates design." },
  205: { decision: 'pass', categories: [], rationale: "Testifying against someone is a common legal context that makes testify unambiguous." },
  206: { decision: 'pass', categories: [], rationale: "Carrying a tracking device gives device a concrete modern object meaning." },
  207: { decision: 'pass', categories: [], rationale: "Asking for financial support is a common request that directly demonstrates financial." },
  208: { decision: 'pass', categories: [], rationale: "A small cluster of cottages in a wood provides a clear group-and-place meaning for cluster." },
  209: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Private methods between classes are programming-specific terms that make access unsuitable as a default context." },
  210: { decision: 'pass', categories: [], rationale: "Fostering an inclusive environment is a common social and educational use that clearly shows inclusive." },
  211: { decision: 'pass', categories: [], rationale: "Landing gear malfunctioning during takeoff gives gear a concrete aircraft-part meaning." },
  212: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Testing bergamot oil purity by mixing it with alcohol is specialist chemistry detail that overwhelms purity." },
  213: { decision: 'pass', categories: [], rationale: "Lack of consensus among speakers is a concise, natural group-decision context." },
  214: { decision: 'pass', categories: [], rationale: "Gargling saltwater to relieve a sore throat gives relieve a familiar, understandable health use." },
  215: { decision: 'pass', categories: [], rationale: "Rare tortoises approaching extinction give verge a clear near-state meaning without graphic detail." },
  216: { decision: 'pass', categories: [], rationale: "Birds eating cat food on a porch provide a concrete, everyday setting for porch." },
  217: { decision: 'pass', categories: [], rationale: "Yelling back for someone is a simple conversational use that clearly demonstrates yell." },
  218: { decision: 'pass', categories: [], rationale: "A motorist rendering aid gives render a clear formal meaning of providing help." },
  219: { decision: 'pass', categories: [], rationale: "An anthropology professor studying social change gives evolution a clear development-over-time meaning." },
  220: { decision: 'pass', categories: [], rationale: "Possessing a strength from grace gives possess a clear figurative ownership meaning." },
  221: { decision: 'pass', categories: [], rationale: "An economy bouncing back after crisis is a familiar recovery context that directly shows bounce." },
  222: { decision: 'pass', categories: [], rationale: "The contrast between normal and abnormal circumstances gives abnormal a clear deviation meaning." },
  223: { decision: 'pass', categories: [], rationale: "The blink of an eye is a familiar idiom that clearly shows blink as a very short moment." },
  224: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "Addiction and an exploitative-system claim make aspect depend on a sensitive medical-policy argument rather than a neutral example." },
  225: { decision: 'pass', categories: [], rationale: "A coalition for change is a simple civic group context that clearly illustrates coalition." },
  226: { decision: 'pass', categories: [], rationale: "Pronouncing a name wrong on purpose gives annoy a direct interpersonal cause-and-effect context." },
  227: { decision: 'reject', categories: ['hate', 'political-heavy'], rationale: "A law banning speech and insulting racial groups makes segment part of a charged legal and hate-speech dispute." },
  228: { decision: 'pass', categories: [], rationale: "Motivating one another to succeed is a clear, everyday use of motivate." },
  229: { decision: 'pass', categories: [], rationale: "Letting an action slide is a common idiom that clearly demonstrates slide in a figurative sense." },
  230: { decision: 'reject', categories: ['specialist-background', 'fantastical-context'], rationale: "Carbon nanotubes and a space elevator require speculative engineering background that overwhelms cable." },
  231: { decision: 'reject', categories: ['violence', 'context-too-hard'], rationale: "Sneaking contraband into prison adds crime and institutional background that is unnecessary for the basic verb sneak." },
  232: { decision: 'pass', categories: [], rationale: "Folding and unfolding along lines to make a crease is a precise, accessible instruction." },
  233: { decision: 'pass', categories: [], rationale: "Diplomatic efforts resolving a crisis give resolve a clear problem-solving meaning in simple language." },
  234: { decision: 'reject', categories: ['context-too-hard', 'public-controversy'], rationale: "Cryptocurrencies and fixed gold or silver exchange create specialist financial context that overwhelms exchange." },
  235: { decision: 'reject', categories: ['unnatural-English'], rationale: "The question has a subject-verb agreement error, so it does not provide a reliable natural model for negative." },
  236: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Transitioning to a gift economy introduces a political-economic concept that is harder than transition and not needed for it." },
  237: { decision: 'reject', categories: ['archaic', 'weak-teaching-value'], rationale: "Reign of mediocrity is an ornate abstract phrase that gives reign little concrete default teaching value." },
  238: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Laser hair removal and electrolysis create specialist cosmetic-medical detail that is unnecessary for benefit." },
  239: { decision: 'pass', categories: [], rationale: "Citing an English-language authority rather than a grammar tool is a clear modern use of cite." },
  240: { decision: 'pass', categories: [], rationale: "Appropriate punctuation is a direct classroom example that clearly shows appropriate." },
  241: { decision: 'reject', categories: ['medical-heavy', 'hate'], rationale: "The sane and mentally ill comparison makes vice depend on stigmatizing medical language rather than a neutral example." },
  242: { decision: 'pass', categories: [], rationale: "Speaking for a small committee is a simple group-work context that directly illustrates committee." },
  243: { decision: 'pass', categories: [], rationale: "An urgent matter for a space crew gives mission a clear purposeful-operation meaning." },
  244: { decision: 'reject', categories: ['specialist-background', 'context-too-hard'], rationale: "Fungicides, rust diseases, and environmental threats create specialist agriculture vocabulary that overwhelms pose." },
  245: { decision: 'reject', categories: ['violence'], rationale: "A robber's demands and personal safety add a threatening crime context that is unnecessary for guarantee." },
  246: { decision: 'pass', categories: [], rationale: "A diploma mill is a recognizable education context that clearly demonstrates diploma." },
  247: { decision: 'pass', categories: [], rationale: "Professional wrestling as performance art gives professional a clear occupation-and-performance meaning." },
  248: { decision: 'pass', categories: [], rationale: "Sustainable gardening inspiring neighbors gives focus a clear attention-and-activity meaning." },
  249: { decision: 'pass', categories: [], rationale: "Electric motors, acceleration, and torque form a coherent accessible engineering context for electric." },
  250: { decision: 'pass', categories: [], rationale: "The sentence directly discusses religion or philosophy without advocating a specific belief, making religion clear." },
  251: { decision: 'reject', categories: ['medical-heavy', 'context-too-hard'], rationale: "Cannabis, antidepressants, and lithium create a specialist drug-interaction context that overwhelms interact." },
  252: { decision: 'pass', categories: [], rationale: "A map helping someone orient themselves is a direct practical example with no extra background." },
  253: { decision: 'pass', categories: [], rationale: "Mountains enduring as people must is a concise, understandable figurative use of endure." },
  254: { decision: 'reject', categories: ['death-heavy', 'context-dependent'], rationale: "Dying without telling a secret makes recipe part of an unresolved death story rather than a neutral food context." },
  255: { decision: 'reject', categories: ['death-heavy', 'context-too-hard'], rationale: "Drought-ravaged regions and inflicting pain on communities add disaster and geographic background that overwhelms inflict." },
  256: { decision: 'reject', categories: ['political-heavy', 'violence'], rationale: "Shoplifting and calling it noble is an ideological criminal claim that is not appropriate as a neutral context for massive." },
  257: { decision: 'pass', categories: [], rationale: "A crisis putting everyone into panic gives panic a clear emotional state meaning." },
  258: { decision: 'pass', categories: [], rationale: "Assurance in the walk of someone who knows their path gives assurance a clear confidence meaning." },
  259: { decision: 'pass', categories: [], rationale: "Holding a hand while promising support gives promising a familiar interpersonal use." },
  260: { decision: 'pass', categories: [], rationale: "Velvet fabric as a sign of luxury gives fabric a concrete material meaning." },
  261: { decision: 'reject', categories: ['political-heavy', 'other'], rationale: "Homelessness and millionaire status create class-emotional load that is unnecessary for a default example of millionaire." },
  262: { decision: 'pass', categories: [], rationale: "The impact of global warming on agriculture is a clear environmental cause-and-effect context." },
  263: { decision: 'pass', categories: [], rationale: "A banknote entering circulation is a direct economic use that clearly shows circulation." },
  264: { decision: 'pass', categories: [], rationale: "Scraping by on income is a natural financial phrase that directly illustrates barely." },
  265: { decision: 'pass', categories: [], rationale: "A donation page asking what the money is for gives donation a clear practical meaning." },
  266: { decision: 'reject', categories: ['archaic', 'weak-teaching-value'], rationale: "No intellectual light from a source is an obscure metaphor that does not present intellectual in a clear modern context." },
  267: { decision: 'reject', categories: ['political-heavy', 'context-too-hard'], rationale: "Drafting a constitution through stakeholder committees is a specialized political-legal context that overwhelms constitution." },
  268: { decision: 'pass', categories: [], rationale: "A tick on a forehead is a concrete animal-parasite reference that makes tick clear." },
  269: { decision: 'pass', categories: [], rationale: "Owls preying on skunks gives prey a clear animal relationship without graphic detail." },
  270: { decision: 'pass', categories: [], rationale: "The question about a limit to human ambition is a direct, accessible abstract example." },
  271: { decision: 'pass', categories: [], rationale: "Being skeptical about knowledge in a physical world gives skeptical a clear questioning attitude." },
  272: { decision: 'pass', categories: [], rationale: "Enrolling in a learning course is a familiar education context that directly shows enroll." },
  273: { decision: 'pass', categories: [], rationale: "A digital voice clone is a contemporary but understandable technology example that clearly teaches clone." },
  274: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Five-dimensional chess is a niche metaphor that adds cultural and fantastical load unrelated to the basic target bizarre." },
  275: { decision: 'pass', categories: [], rationale: "Calling behavior asinine is a direct and familiar evaluative use of behavior." },
  276: { decision: 'pass', categories: [], rationale: "Signing a new lease is a common housing transaction that makes lease clear." },
  277: { decision: 'pass', categories: [], rationale: "An opponent tapping out is a recognizable sports context that directly illustrates opponent." },
  278: { decision: 'pass', categories: [], rationale: "Stowing carry-on luggage overhead is a concrete travel instruction that clearly shows luggage." },
  279: { decision: 'pass', categories: [], rationale: "Loyalty as a key to lasting love gives loyalty a familiar relationship meaning." },
  280: { decision: 'reject', categories: ['medical-heavy', 'public-controversy'], rationale: "A psych ward and trans people create sensitive medical and identity-policy context unrelated to teaching ward." },
  281: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "Suffice to say is a formulaic discourse fragment followed by an unexplained horrible night, so the target is not taught standalone." },
  282: { decision: 'reject', categories: ['medical-heavy', 'hate'], rationale: "Bipolar people are used in a stigmatizing claim about threatening minorities, adding medical and identity harm unrelated to threaten." },
  283: { decision: 'pass', categories: [], rationale: "Not understanding French well enough to evaluate poetry gives evaluate a clear judgment meaning." },
  284: { decision: 'pass', categories: [], rationale: "A conservation issue involving people and animals gives issue a clear public-problem meaning." },
  285: { decision: 'reject', categories: ['violence', 'weak-teaching-value'], rationale: "Punishing a child makes permissible depend on a violence-adjacent parenting dispute that is unnecessary for the target." },
  286: { decision: 'pass', categories: [], rationale: "A maverick disregard for protocol gives disregard a clear attitude toward rules." },
  287: { decision: 'pass', categories: [], rationale: "Maintaining peace and stability in a galaxy gives stability a clear condition-of-order meaning." },
  288: { decision: 'reject', categories: ['religious-heavy', 'archaic'], rationale: "Catholic priests and shaved heads create a religious historical context that is unnecessary for a default example of catholic." },
  289: { decision: 'pass', categories: [], rationale: "Not being immune to propaganda is a concise, direct civic-media context that clearly teaches propaganda." },
  290: { decision: 'pass', categories: [], rationale: "A boring lecture causing sleepiness gives boring a familiar classroom context." },
  291: { decision: 'reject', categories: ['death-heavy', 'context-dependent'], rationale: "Tom's unexplained sacrifice is emotionally loaded and ambiguous, so sacrifice lacks a clear standalone teaching context." },
  292: { decision: 'pass', categories: [], rationale: "Data protection being crucial in the modern age is a clear contemporary importance context." },
  293: { decision: 'reject', categories: ['unnatural-English'], rationale: "The sentence says vocal chords instead of the standard vocal cords, so it is not a reliable natural English model." },
  294: { decision: 'pass', categories: [], rationale: "One potato being definitely bad is a simple, concrete example of definitely." },
  295: { decision: 'pass', categories: [], rationale: "Bronze and terracotta artifacts give bronze a clear material-and-history context." },
  296: { decision: 'pass', categories: [], rationale: "A justice-system trial is a direct legal context that clearly shows trial." },
  297: { decision: 'pass', categories: [], rationale: "Changing lanes without a turn signal is a familiar driving situation that clearly demonstrates signal." },
}

function rubricFor(decision: Decision, categories: string[]): Record<string, string> {
  const has = (names: string[]) => names.some((name) => categories.includes(name))
  return {
    defaultLearningAppropriateness: decision === 'pass' ? 'YES' : 'NO',
    targetTeachingValue: has(['weak-teaching-value', 'rare-sense']) ? 'FAIL' : 'PASS',
    contextVocabularyLoad: has(['context-too-hard', 'specialist-background', 'proper-noun-heavy']) ? 'FAIL' : 'PASS',
    syntaxSimplicity: has(['syntax-too-complex']) ? 'FAIL' : 'PASS',
    standaloneClarity: has(['context-dependent']) ? 'FAIL' : 'PASS',
    topicNeutrality: has(['political-heavy', 'medical-heavy', 'death-heavy', 'violence', 'extremism', 'hate', 'public-controversy', 'sexual', 'self-harm']) ? 'FAIL' : 'PASS',
    naturalModernEnglish: has(['unnatural-English', 'archaic', 'fantastical-context']) ? 'FAIL' : 'PASS',
    finalEditorDecision: decision === 'pass' ? 'PASS' : 'FAIL',
  }
}

function flags(trace: Provenance): Record<string, number> {
  return Object.fromEntries(Object.entries(trace).filter(([, value]) => typeof value === 'number')) as Record<string, number>
}

function csvCell(value: unknown): string {
  const text = typeof value === 'string' ? value : JSON.stringify(value)
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text
}

const candidates = JSON.parse(await readFile(candidatePath, 'utf8')) as { seed: number; rows: Candidate[] }
const provenance = JSON.parse(await readFile(provenancePath, 'utf8')) as Record<string, Provenance>
// The authored map was drafted in three visible batches and skipped two rows
// during transcription. Reconcile those omissions explicitly before joining
// decisions to candidates; never allow a shifted rationale to silently pass.
const normalizedDecisions: Record<number, ManualDecision> = {}
for (const [authoredIndexText, decision] of Object.entries(decisions)) {
  const authoredIndex = Number(authoredIndexText)
  const candidateIndex = authoredIndex < 35 ? authoredIndex : authoredIndex < 204 ? authoredIndex + 1 : authoredIndex + 2
  normalizedDecisions[candidateIndex] = decision
}
normalizedDecisions[35] = {
  decision: 'pass',
  categories: [],
  rationale: "Peeking into a medicine cabinet is a familiar household action that gives cabinet a clear, concrete storage meaning.",
}
normalizedDecisions[205] = {
  decision: 'pass',
  categories: [],
  rationale: "Not hesitating to ask for clarification is a natural, supportive conversation context that clearly demonstrates hesitate.",
}
if (candidates.rows.length !== 300 || Object.keys(normalizedDecisions).length !== 300) throw new Error(`Post-curation review count mismatch: candidates=${candidates.rows.length}; decisions=${Object.keys(normalizedDecisions).length}`)
const rows = candidates.rows.map((candidate, index) => {
  const decision = normalizedDecisions[index]
  const trace = provenance[candidate.word]
  if (!decision || !trace || trace.sentenceId !== candidate.sentenceId) throw new Error(`Post-curation decision/provenance mismatch at ${index}: ${candidate.word}|${candidate.sentenceId}`)
  return {
    ...candidate,
    seed: candidates.seed,
    decision: decision.decision,
    categories: decision.categories,
    rationale: decision.rationale,
    reviewer: 'Lula-agent',
    reviewBasis: 'sentence-read-semantic-rubric',
    semanticDecisionSource: 'sentence-read',
    rubric: rubricFor(decision.decision, decision.categories),
    machineFlags: flags(trace),
    severeInappropriate: index === 24 ? true : false,
  }
})
const rationales = rows.map((row) => row.rationale)
const frequencies = new Map<string, number>()
for (const rationale of rationales) frequencies.set(rationale, (frequencies.get(rationale) ?? 0) + 1)
const exactDuplicateRationaleCount = [...frequencies.values()].filter((count) => count > 1).reduce((total, count) => total + count - 1, 0)
const genericRationaleCount = rationales.filter((rationale) => rationale.length < 60 || /^Read in full:/i.test(rationale) || /^This is complete and natural/i.test(rationale)).length
const rationaleQuality = {
  reviewedRows: rows.length,
  exactDuplicateRationaleCount,
  genericRationaleCount,
  genericRationaleShare: Number((genericRationaleCount / rows.length).toFixed(4)),
  gate: exactDuplicateRationaleCount <= 5 && genericRationaleCount / rows.length < 0.05,
  method: 'Audit-only reviewer-quality QA; it never creates or changes semantic decisions.',
}
const columns = ['word', 'sentenceId', 'sentence', 'decision', 'categories', 'rationale', 'reviewType', 'seed', 'semanticDecisionSource', 'defaultLearningAppropriateness', 'targetTeachingValue', 'contextVocabularyLoad', 'syntaxSimplicity', 'standaloneClarity', 'topicNeutrality', 'naturalModernEnglish', 'finalEditorDecision', 'severeInappropriate']
const csv = `${columns.join(',')}\n${rows.map((row) => columns.map((column) => column === 'categories' ? csvCell(row.categories.join('; ')) : Object.prototype.hasOwnProperty.call(row.rubric, column) ? csvCell(row.rubric[column]) : csvCell((row as Record<string, unknown>)[column])).join(',')).join('\n')}\n`

await mkdir(auditRoot, { recursive: true })
await writeFile(resolve(auditRoot, 'phase-a-post-curation-review.json'), `${JSON.stringify({
  round: 'Context Final Semantic Acceptance - Round 5',
  seed: candidates.seed,
  sampleSize: rows.length,
  semanticDecisionSource: 'sentence-read',
  machineMetricsRole: 'triage metadata only; never used to assign decision',
  rows,
}, null, 2)}\n`, 'utf8')
await writeFile(resolve(auditRoot, 'phase-a-post-curation-review.csv'), csv, 'utf8')
await writeFile(resolve(auditRoot, 'rationale-quality-report-post-curation.json'), `${JSON.stringify(rationaleQuality, null, 2)}\n`, 'utf8')
console.log(`Round 5 post-curation review written: sample=${rows.length}, fails=${rows.filter((row) => row.decision === 'reject').length}, severe=${rows.filter((row) => row.severeInappropriate).length}, rationaleDuplicates=${exactDuplicateRationaleCount}, genericShare=${(rationaleQuality.genericRationaleShare * 100).toFixed(1)}%`)
