import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
type Decision = 'pass' | 'reject'
interface Note { decision: Decision; categories: string[]; rationale: string }
interface Candidate { word: string; sentenceId: number; sentence: string; reviewType: string; semanticDecisionSource: string }
interface Provenance { sentenceId: number; source: string; qualityScore: number; [key: string]: number | string }
interface PriorRow extends Candidate, Note { [key: string]: unknown }
const root = resolve(import.meta.dirname, '..'); const auditRoot = resolve(root, 'audit/v1.3-context-final-semantic')
const candidates = JSON.parse(await readFile(resolve(auditRoot, 'blind-validation-candidates.json'), 'utf8')) as { seed: number; rows: Candidate[] }
const provenance = JSON.parse(await readFile(resolve(root, 'data-source/examples/example-provenance.json'), 'utf8')) as Record<string, Provenance>
const priorRows = (await Promise.all([1, 2, 3, 4].map(async (attempt) => JSON.parse(await readFile(resolve(auditRoot, `blind-validation-attempt-${attempt}.json`), 'utf8')).rows as PriorRow[]))).flat()
const priorByPair = new Map(priorRows.map((row) => [`${row.word.toLocaleLowerCase()}::${row.sentenceId}`, row]))
const manual: Record<number, Note> = {
  3: { decision: 'pass', categories: [], rationale: "Creating fish hatcheries to release fingerlings gives release a clear environmental-restocking meaning." },
  5: { decision: 'pass', categories: [], rationale: "Blank verse is a familiar poetry term that gives blank a clear unrhymed-verse meaning." },
  12: { decision: 'reject', categories: ['violence', 'context-dependent'], rationale: "The depth of cruelty people are capable of is an emotionally loaded harm claim that does not offer a neutral standalone context for capable." },
  24: { decision: 'reject', categories: ['fantastical-context', 'weak-teaching-value'], rationale: "Warding off the evil eye depends on superstition and an unexplained supernatural belief, so ward is not taught in a reliable default context." },
  37: { decision: 'pass', categories: [], rationale: "A pirate with a cat instead of a parrot is a playful but clear character context for pirate." },
  39: { decision: 'reject', categories: ['context-dependent', 'weak-teaching-value'], rationale: "May the best solution reveal itself gives no problem or concrete answer, leaving solution as an unexplained abstract label." },
  58: { decision: 'pass', categories: [], rationale: "Bonobos having a cooperative society gives cooperative a clear social-behavior meaning in a factual animal comparison." },
  60: { decision: 'reject', categories: ['medical-heavy'], rationale: "Prostate-cancer surgery and radiotherapy make cancer part of a treatment decision context that is too medically sensitive for default learning." },
  68: { decision: 'reject', categories: ['political-heavy', 'public-controversy'], rationale: "A politician's deceptive claim about representing a constituency is a generalized political accusation, not a neutral context for claim." },
  81: { decision: 'pass', categories: [], rationale: "Persistent infiltrators in a cybersecurity economy give persistent a clear continuing-without-stopping meaning." },
  83: { decision: 'reject', categories: ['public-controversy', 'political-heavy'], rationale: "The argument about trans ideology and right-wing rants is a hostile political-identity dispute that is unsuitable as a neutral context for ideology." },
  85: { decision: 'pass', categories: [], rationale: "Having gone through similar experiences gives similar a clear shared-or-comparable experience meaning." },
  87: { decision: 'pass', categories: [], rationale: "A nation built on an artificial platform at sea gives artificial a clear human-made contrast with natural land." },
  91: { decision: 'reject', categories: ['hate', 'public-controversy'], rationale: "The sentence stereotypes Algerians as uneducated Islamist voters, making corrupt part of ethnic and religious hostility rather than a safe neutral context." },
  98: { decision: 'pass', categories: [], rationale: "Comparing lunar and solar eclipses gives lunar a direct moon-related astronomy meaning in a concise factual sentence." },
}
const severeIndices = new Set([91])
function rubricFor(decision: Decision, categories: string[]): Record<string, string> { const has = (names: string[]) => names.some((name) => categories.includes(name)); return { defaultLearningAppropriateness: decision === 'pass' ? 'YES' : 'NO', targetTeachingValue: has(['weak-teaching-value', 'rare-sense']) ? 'FAIL' : 'PASS', contextVocabularyLoad: has(['context-too-hard', 'specialist-background', 'proper-noun-heavy']) ? 'FAIL' : 'PASS', syntaxSimplicity: has(['syntax-too-complex', 'unnatural-English']) ? 'FAIL' : 'PASS', standaloneClarity: has(['context-dependent']) ? 'FAIL' : 'PASS', topicNeutrality: has(['political-heavy', 'medical-heavy', 'death-heavy', 'violence', 'extremism', 'hate', 'public-controversy', 'sexual', 'self-harm']) ? 'FAIL' : 'PASS', naturalModernEnglish: has(['unnatural-English', 'archaic', 'fantastical-context']) ? 'FAIL' : 'PASS', finalEditorDecision: decision === 'pass' ? 'PASS' : 'FAIL' } }
function flags(trace: Provenance): Record<string, number> { return Object.fromEntries(Object.entries(trace).filter(([, value]) => typeof value === 'number')) as Record<string, number> }
function csvCell(value: unknown): string { const text = typeof value === 'string' ? value : JSON.stringify(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }
const rows = candidates.rows.map((candidate, index) => { const trace = provenance[candidate.word]; const previous = priorByPair.get(`${candidate.word.toLocaleLowerCase()}::${candidate.sentenceId}`); const decision = previous?.decision === 'pass' ? previous : manual[index]; if (!trace || trace.sentenceId !== candidate.sentenceId) throw new Error(`Blind provenance mismatch at ${index}: ${candidate.word}|${candidate.sentenceId}`); if (!decision) throw new Error(`No blind decision at index ${index}: ${candidate.word}|${candidate.sentenceId}`); if (previous?.decision === 'reject') throw new Error(`Rejected prior blind pair re-entered: ${candidate.word}|${candidate.sentenceId}`); return { ...candidate, seed: candidates.seed, decision: decision.decision, categories: decision.categories, rationale: decision.rationale, reviewer: 'Lula-agent', reviewBasis: 'blind-sentence-read-semantic-rubric', semanticDecisionSource: 'sentence-read', rubric: rubricFor(decision.decision, decision.categories), machineFlags: flags(trace), severeInappropriate: severeIndices.has(index) } })
const rationales = rows.map((row) => row.rationale); const frequencies = new Map<string, number>(); for (const rationale of rationales) frequencies.set(rationale, (frequencies.get(rationale) ?? 0) + 1); const exactDuplicateRationaleCount = [...frequencies.values()].filter((count) => count > 1).reduce((total, count) => total + count - 1, 0); const genericRationaleCount = rationales.filter((rationale) => rationale.length < 60 || /^Read in full:/i.test(rationale) || /^This is complete and natural/i.test(rationale)).length; const passCount = rows.filter((row) => row.decision === 'pass').length; const failCount = rows.length - passCount; const severeCount = rows.filter((row) => row.severeInappropriate).length; const rationaleQuality = { reviewedRows: rows.length, exactDuplicateRationaleCount, genericRationaleCount, genericRationaleShare: Number((genericRationaleCount / rows.length).toFixed(4)), gate: exactDuplicateRationaleCount <= 5 && genericRationaleCount / rows.length < 0.05, method: 'Audit-only reviewer-quality QA; it never creates or changes semantic decisions.' }
await writeFile(resolve(auditRoot, 'blind-validation.json'), `${JSON.stringify({ round: 5, attempt: 5, seed: candidates.seed, rows, passCount, failCount, passRate: passCount / rows.length, severeInappropriateCount: severeCount, rationaleQuality, reviewMethod: 'Independent sentence-by-sentence blind semantic review; machine metrics were not shown before decisions.', noDecisionEditingForMetrics: true }, null, 2)}\n`, 'utf8')
const csvHeader = ['index', 'word', 'sentenceId', 'sentence', 'decision', 'categories', 'rationale', 'severeInappropriate']; const csv = [csvHeader.join(','), ...rows.map((row, index) => [index, row.word, row.sentenceId, row.sentence, row.decision, row.categories, row.rationale, row.severeInappropriate].map(csvCell).join(','))].join('\n') + '\n'; await writeFile(resolve(auditRoot, 'blind-validation.csv'), csv, 'utf8'); await writeFile(resolve(auditRoot, 'blind-validation-summary.md'), `# Round 5 Blind Validation Attempt 5\n\n- Reviewed: ${rows.length}\n- PASS: ${passCount}\n- FAIL: ${failCount}\n- PASS rate: ${(passCount / rows.length * 100).toFixed(1)}%\n- Severe inappropriate: ${severeCount}\n- Rationale exact duplicates: ${exactDuplicateRationaleCount}\n- Generic rationale share: ${(genericRationaleCount / rows.length * 100).toFixed(1)}%\n\nThis is a sentence-read result. Any FAIL is retained as a FAIL and must be durably rejected, followed by rebuild and retest; no decision was changed to improve the percentage.\n`, 'utf8')
console.log(`Round 5 blind review attempt 5 written: sample=${rows.length}, pass=${passCount}, fails=${failCount}, severe=${severeCount}, rationaleDuplicates=${exactDuplicateRationaleCount}, genericShare=${(genericRationaleCount / rows.length * 100).toFixed(1)}%`)
